"""Tests for the git hooks installer module."""

import os
import shlex
import stat
import subprocess
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from gobby.cli.installers.git_hooks import (
    GOBBY_HOOK_END,
    GOBBY_HOOK_START,
    HOOK_TEMPLATES,
    _backup_hook,
    _check_precommit_installed,
    _has_gobby_hook,
    _has_precommit_config,
    _is_precommit_framework_hook,
    _remove_gobby_section,
    _resolve_git_hooks_dir,
    _wrap_gobby_section,
    install_git_hooks,
    uninstall_git_hooks,
)

pytestmark = pytest.mark.unit


class TestHasGobbyHook:
    """Tests for _has_gobby_hook function."""

    def test_returns_true_when_marker_present(self) -> None:
        """Test that function returns True when Gobby marker is present."""
        content = f"""#!/bin/bash
{GOBBY_HOOK_START}
# some hook content
{GOBBY_HOOK_END}
"""
        assert _has_gobby_hook(content) is True

    def test_returns_false_when_marker_absent(self) -> None:
        """Test that function returns False when Gobby marker is absent."""
        content = """#!/bin/bash
# some other hook content
echo "hello"
"""
        assert _has_gobby_hook(content) is False

    def test_returns_false_for_empty_content(self) -> None:
        """Test that function returns False for empty content."""
        assert _has_gobby_hook("") is False

    def test_partial_marker_returns_false(self) -> None:
        """Test that partial marker doesn't match."""
        content = """#!/bin/bash
# >>> GOBBY
"""
        assert _has_gobby_hook(content) is False


class TestIsPrecommitFrameworkHook:
    """Tests for _is_precommit_framework_hook function."""

    def test_detects_precommit_generated_hook(self) -> None:
        """Test detection of pre-commit framework generated hook."""
        content = """#!/usr/bin/env python
# File generated by pre-commit: https://pre-commit.com
import sys
"""
        assert _is_precommit_framework_hook(content) is True

    def test_detects_precommit_module_usage(self) -> None:
        """Test detection of pre_commit module usage."""
        content = """#!/usr/bin/env python
import pre_commit
from pre_commit import main
"""
        assert _is_precommit_framework_hook(content) is True

    def test_returns_false_for_regular_hook(self) -> None:
        """Test that regular hooks are not detected as pre-commit."""
        content = """#!/bin/bash
echo "Running tests..."
npm test
"""
        assert _is_precommit_framework_hook(content) is False

    def test_returns_false_for_empty_content(self) -> None:
        """Test that empty content returns False."""
        assert _is_precommit_framework_hook("") is False


class TestWrapGobbySection:
    """Tests for _wrap_gobby_section function."""

    def test_wraps_script_with_markers(self) -> None:
        """Test that script is wrapped with start and end markers."""
        script = """
echo "hello"
"""
        result = _wrap_gobby_section(script)

        assert result.startswith(GOBBY_HOOK_START)
        assert result.endswith(GOBBY_HOOK_END + "\n")
        assert 'echo "hello"' in result

    def test_strips_whitespace_from_script(self) -> None:
        """Test that leading/trailing whitespace is stripped."""
        script = """

   echo "test"

"""
        result = _wrap_gobby_section(script)

        # Should not have blank lines at start/end within markers
        lines = result.split("\n")
        assert lines[1] == 'echo "test"'

    def test_handles_multiline_script(self) -> None:
        """Test wrapping a multiline script."""
        script = """
line1
line2
line3
"""
        result = _wrap_gobby_section(script)

        assert "line1" in result
        assert "line2" in result
        assert "line3" in result


class TestRemoveGobbySection:
    """Tests for _remove_gobby_section function."""

    def test_removes_gobby_section_completely(self) -> None:
        """Test that Gobby section is removed completely."""
        content = f"""#!/bin/bash
echo "before"
{GOBBY_HOOK_START}
# gobby hook content
echo "gobby stuff"
{GOBBY_HOOK_END}
echo "after"
"""
        result = _remove_gobby_section(content)

        assert GOBBY_HOOK_START not in result
        assert GOBBY_HOOK_END not in result
        assert "gobby stuff" not in result
        assert "before" in result
        assert "after" in result

    def test_preserves_content_outside_section(self) -> None:
        """Test that content outside Gobby section is preserved."""
        content = f"""#!/bin/bash
echo "first"
{GOBBY_HOOK_START}
# gobby
{GOBBY_HOOK_END}
echo "second"
"""
        result = _remove_gobby_section(content)

        assert "first" in result
        assert "second" in result

    def test_handles_content_without_gobby_section(self) -> None:
        """Test handling content that has no Gobby section."""
        content = """#!/bin/bash
echo "no gobby here"
"""
        result = _remove_gobby_section(content)

        assert "no gobby here" in result

    def test_returns_empty_for_gobby_only_content(self) -> None:
        """Test that returns empty when only Gobby section exists."""
        content = f"""{GOBBY_HOOK_START}
# gobby content only
{GOBBY_HOOK_END}
"""
        result = _remove_gobby_section(content)

        assert result == ""

    def test_cleans_up_multiple_blank_lines(self) -> None:
        """Test that multiple consecutive blank lines are reduced."""
        content = f"""#!/bin/bash


{GOBBY_HOOK_START}
# gobby
{GOBBY_HOOK_END}



echo "after"
"""
        result = _remove_gobby_section(content)

        # Should not have more than 2 consecutive newlines
        assert "\n\n\n" not in result


class TestBackupHook:
    """Tests for _backup_hook function."""

    def test_creates_timestamped_backup(self, tmp_path: Path) -> None:
        """Test that backup is created with timestamp."""
        hooks_dir = tmp_path / "hooks"
        hooks_dir.mkdir()

        hook_path = hooks_dir / "pre-commit"
        hook_path.write_text("#!/bin/bash\necho 'original'")

        backup_path = _backup_hook(hook_path, hooks_dir)

        assert backup_path is not None
        assert Path(backup_path).exists()
        assert ".backup" in backup_path
        assert Path(backup_path).read_text() == "#!/bin/bash\necho 'original'"

    def test_returns_none_for_nonexistent_hook(self, tmp_path: Path) -> None:
        """Test that None is returned when hook doesn't exist."""
        hooks_dir = tmp_path / "hooks"
        hooks_dir.mkdir()

        hook_path = hooks_dir / "nonexistent"

        result = _backup_hook(hook_path, hooks_dir)

        result = _backup_hook(hook_path, hooks_dir)

        assert result is None

    def test_backup_preserves_metadata(self, tmp_path: Path) -> None:
        """Test that backup preserves file metadata (copy2)."""
        hooks_dir = tmp_path / "hooks"
        hooks_dir.mkdir()

        hook_path = hooks_dir / "pre-commit"
        hook_path.write_text("#!/bin/bash")
        # Set specific permissions
        hook_path.chmod(stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP)

        backup_path = _backup_hook(hook_path, hooks_dir)

        assert backup_path is not None
        backup = Path(backup_path)
        # Permissions should be preserved
        original_mode = hook_path.stat().st_mode
        backup_mode = backup.stat().st_mode
        assert (original_mode & 0o777) == (backup_mode & 0o777)

    @patch("gobby.cli.installers.git_hooks.shutil.copy2")
    def test_handles_os_error_gracefully(self, mock_copy: MagicMock, tmp_path: Path) -> None:
        """Test that OSError during backup is handled gracefully."""
        hooks_dir = tmp_path / "hooks"
        hooks_dir.mkdir()

        hook_path = hooks_dir / "pre-commit"
        hook_path.write_text("#!/bin/bash")

        mock_copy.side_effect = OSError("Permission denied")

        result = _backup_hook(hook_path, hooks_dir)

        assert result is None


class TestCheckPrecommitInstalled:
    """Tests for _check_precommit_installed function."""

    @patch("gobby.cli.installers.git_hooks.shutil.which")
    def test_returns_true_when_precommit_installed(self, mock_which: MagicMock) -> None:
        """Test returns True when pre-commit is in PATH."""
        mock_which.return_value = "/usr/local/bin/pre-commit"

        assert _check_precommit_installed() is True
        mock_which.assert_called_once_with("pre-commit")

    @patch("gobby.cli.installers.git_hooks.shutil.which")
    def test_returns_false_when_precommit_not_installed(self, mock_which: MagicMock) -> None:
        """Test returns False when pre-commit is not in PATH."""
        mock_which.return_value = None

        assert _check_precommit_installed() is False


class TestHasPrecommitConfig:
    """Tests for _has_precommit_config function."""

    def test_returns_true_when_config_exists(self, tmp_path: Path) -> None:
        """Test returns True when .pre-commit-config.yaml exists."""
        config_file = tmp_path / ".pre-commit-config.yaml"
        config_file.write_text("repos: []")

        assert _has_precommit_config(tmp_path) is True

    def test_returns_false_when_config_missing(self, tmp_path: Path) -> None:
        """Test returns False when .pre-commit-config.yaml doesn't exist."""
        assert _has_precommit_config(tmp_path) is False


class TestInstallGitHooks:
    """Tests for install_git_hooks function."""

    def test_fails_if_not_git_repository(self, tmp_path: Path) -> None:
        """Test that installation fails if not in a git repository."""
        result = install_git_hooks(tmp_path)

        assert result["success"] is False
        assert "Not a git repository" in result["error"]

    def test_creates_hooks_directory_if_missing(self, tmp_path: Path) -> None:
        """Test that .git/hooks directory is created if missing."""
        git_dir = tmp_path / ".git"
        git_dir.mkdir()

        install_git_hooks(tmp_path)

        assert (git_dir / "hooks").exists()

    def test_resolves_hooks_dir_for_linked_worktree(self, tmp_path: Path) -> None:
        """Test that linked worktree .git files use the common hooks directory."""
        worktree = tmp_path / "worktree"
        git_dir = tmp_path / "main" / ".git" / "worktrees" / "worktree"
        common_dir = tmp_path / "main" / ".git"
        worktree.mkdir()
        git_dir.mkdir(parents=True)
        (worktree / ".git").write_text(f"gitdir: {git_dir}\n", encoding="utf-8")
        (git_dir / "commondir").write_text("../..\n", encoding="utf-8")

        result = install_git_hooks(worktree)

        assert result["success"] is True
        assert _resolve_git_hooks_dir(worktree) == common_dir / "hooks"
        assert (common_dir / "hooks" / "pre-commit").exists()

    def test_installs_all_hook_types(self, tmp_path: Path) -> None:
        """Test that all hook types are installed."""
        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        result = install_git_hooks(tmp_path)

        assert result["success"] is True
        assert set(result["installed"]) == set(HOOK_TEMPLATES.keys())

        for hook_name in HOOK_TEMPLATES:
            hook_path = hooks_dir / hook_name
            assert hook_path.exists()

    def test_hooks_are_executable(self, tmp_path: Path) -> None:
        """Test that installed hooks have executable permission."""
        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        install_git_hooks(tmp_path)

        for hook_name in HOOK_TEMPLATES:
            hook_path = hooks_dir / hook_name
            mode = hook_path.stat().st_mode
            assert mode & stat.S_IXUSR  # User executable

    def test_hooks_have_bash_shebang(self, tmp_path: Path) -> None:
        """Test that hooks have proper bash shebang."""
        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        install_git_hooks(tmp_path)

        for hook_name in HOOK_TEMPLATES:
            hook_path = hooks_dir / hook_name
            content = hook_path.read_text()
            assert content.startswith("#!/usr/bin/env bash")

    def test_skips_already_installed_hooks(self, tmp_path: Path) -> None:
        """Test that already installed hooks are skipped."""
        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        # Install first time
        install_git_hooks(tmp_path)

        # Install second time
        result = install_git_hooks(tmp_path)

        assert result["success"] is True
        assert len(result["installed"]) == 0
        assert len(result["skipped"]) == len(HOOK_TEMPLATES)

        for skipped in result["skipped"]:
            assert "already installed" in skipped

    def test_force_reinstalls_existing_hooks(self, tmp_path: Path) -> None:
        """Test that force=True reinstalls existing hooks."""
        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        # Install first time
        install_git_hooks(tmp_path)

        # Install with force
        result = install_git_hooks(tmp_path, force=True)

        assert result["success"] is True
        assert set(result["installed"]) == set(HOOK_TEMPLATES.keys())
        assert len(result["backups"]) > 0

    def test_chains_with_existing_hooks(self, tmp_path: Path) -> None:
        """Test that Gobby hooks chain with existing hooks."""
        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        # Create existing hook
        existing_hook = hooks_dir / "pre-commit"
        existing_hook.write_text("#!/bin/bash\necho 'existing hook'\n")
        existing_hook.chmod(stat.S_IRWXU)

        result = install_git_hooks(tmp_path)

        assert result["success"] is True

        content = existing_hook.read_text()
        # Should contain both original and Gobby sections
        assert "existing hook" in content
        assert GOBBY_HOOK_START in content

    def test_preserves_shebang_when_chaining(self, tmp_path: Path) -> None:
        """Test that existing shebang is preserved when chaining."""
        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        # Create existing hook with specific shebang
        existing_hook = hooks_dir / "pre-push"
        existing_hook.write_text("#!/usr/bin/env zsh\necho 'zsh hook'\n")

        install_git_hooks(tmp_path)

        content = existing_hook.read_text()
        # Should preserve the original shebang
        assert content.startswith("#!/usr/bin/env zsh")

    def test_creates_backup_before_modifying(self, tmp_path: Path) -> None:
        """Test that backup is created before modifying existing hook."""
        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        # Create existing hook
        existing_hook = hooks_dir / "pre-commit"
        original_content = "#!/bin/bash\necho 'original'\n"
        existing_hook.write_text(original_content)

        result = install_git_hooks(tmp_path, force=True)

        assert len(result["backups"]) > 0
        backup_path = result["backups"][0]
        assert Path(backup_path).read_text() == original_content

    def test_replaces_precommit_framework_hook(self, tmp_path: Path) -> None:
        """Test that pre-commit framework hook is replaced with wrapper."""
        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        # Create pre-commit framework generated hook
        precommit_hook = hooks_dir / "pre-commit"
        precommit_hook.write_text(
            "#!/usr/bin/env python\n# File generated by pre-commit\nimport pre_commit\n"
        )

        result = install_git_hooks(tmp_path)

        assert result["success"] is True

        content = precommit_hook.read_text()
        # Should replace entirely, not chain
        assert "File generated by pre-commit" not in content
        assert GOBBY_HOOK_START in content

    @patch("gobby.cli.installers.git_hooks._backup_hook")
    def test_continues_when_backup_fails(self, mock_backup: MagicMock, tmp_path: Path) -> None:
        """Test that installation continues even when backup fails."""
        mock_backup.return_value = None  # Simulate backup failure

        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        # Create existing hook
        existing_hook = hooks_dir / "pre-commit"
        existing_hook.write_text("#!/bin/bash\necho 'existing'\n")

        result = install_git_hooks(tmp_path, force=True)

        assert result["success"] is True
        assert "pre-commit" in result["installed"]
        # No backups should be recorded since backup failed
        assert len(result["backups"]) == 0

        # Hook should still be updated
        content = existing_hook.read_text()
        assert GOBBY_HOOK_START in content

    @patch("gobby.cli.installers.git_hooks._check_precommit_installed")
    def test_installs_pre_push_hooks_when_precommit_available(
        self, mock_check: MagicMock, tmp_path: Path
    ) -> None:
        """Test that pre-push hooks are NOT installed via pre-commit CLI (handled by wrapper)."""
        mock_check.return_value = True

        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        # Create pre-commit config
        (tmp_path / ".pre-commit-config.yaml").write_text("repos: []")

        result = install_git_hooks(tmp_path, setup_precommit=True)

        assert result["success"] is True
        assert result["precommit_installed"] is True

    @patch("gobby.cli.installers.git_hooks._check_precommit_installed")
    def test_skips_precommit_when_not_installed(
        self, mock_check: MagicMock, tmp_path: Path
    ) -> None:
        """Test that pre-commit setup is skipped when not installed."""
        mock_check.return_value = False

        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        # Create pre-commit config (but pre-commit not installed)
        (tmp_path / ".pre-commit-config.yaml").write_text("repos: []")

        result = install_git_hooks(tmp_path, setup_precommit=True)

        assert result["success"] is True
        assert result["precommit_installed"] is False

    @patch("gobby.cli.installers.git_hooks._check_precommit_installed")
    def test_skips_precommit_when_config_missing(
        self, mock_check: MagicMock, tmp_path: Path
    ) -> None:
        """Test that pre-commit setup is skipped when config is missing."""
        mock_check.return_value = True

        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        result = install_git_hooks(tmp_path, setup_precommit=True)

        assert result["success"] is True
        assert result["precommit_installed"] is False

    def test_skips_precommit_when_setup_disabled(self, tmp_path: Path) -> None:
        """Test that pre-commit setup is skipped when disabled."""
        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        (tmp_path / ".pre-commit-config.yaml").write_text("repos: []")

        result = install_git_hooks(tmp_path, setup_precommit=False)

        assert result["success"] is True
        assert result["precommit_installed"] is False

    def test_hook_content_includes_gobby_markers(self, tmp_path: Path) -> None:
        """Test that installed hooks contain Gobby markers."""
        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        install_git_hooks(tmp_path)

        for hook_name in HOOK_TEMPLATES:
            hook_path = hooks_dir / hook_name
            content = hook_path.read_text()
            assert GOBBY_HOOK_START in content
            assert GOBBY_HOOK_END in content

    def test_adds_shebang_to_existing_hook_without_shebang(self, tmp_path: Path) -> None:
        """Test that shebang is added to existing hooks without one."""
        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        # Create existing hook without shebang
        existing_hook = hooks_dir / "post-commit"
        existing_hook.write_text("echo 'no shebang'\n")

        install_git_hooks(tmp_path)

        content = existing_hook.read_text()
        # Should add shebang at start
        assert content.startswith("#!/usr/bin/env bash")

    def test_handles_empty_existing_hook(self, tmp_path: Path) -> None:
        """Test installing to an existing hook file that is empty."""
        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        # Create empty hook file
        empty_hook = hooks_dir / "post-commit"
        empty_hook.write_text("")

        result = install_git_hooks(tmp_path)

        assert result["success"] is True

        content = empty_hook.read_text()
        assert content.startswith("#!/usr/bin/env bash")
        assert GOBBY_HOOK_START in content

    def test_handles_whitespace_only_existing_hook(self, tmp_path: Path) -> None:
        """Test installing to an existing hook file with only whitespace."""
        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        # Create hook file with only whitespace
        whitespace_hook = hooks_dir / "pre-merge-commit"
        whitespace_hook.write_text("   \n\n  \n")

        result = install_git_hooks(tmp_path)

        assert result["success"] is True

        content = whitespace_hook.read_text()
        assert content.startswith("#!/usr/bin/env bash")
        assert GOBBY_HOOK_START in content

    def test_installs_post_history_hooks_for_index_freshness(self, tmp_path: Path) -> None:
        """Fresh installs create post-history hooks for immediate code reindexing."""
        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        result = install_git_hooks(tmp_path)

        assert result["success"] is True
        for hook_name in ("post-checkout", "post-merge", "post-rewrite"):
            assert hook_name in result["installed"]
            content = (hooks_dir / hook_name).read_text()
            assert (
                'xargs -0 "$GCODE" index --quiet --skip-if-locked --files >/dev/null 2>&1'
            ) in content
            assert "/api/code-index/codewiki/refresh" not in content
            assert "GOBBY HOOK START" in content

    def test_post_checkout_reindexes_changed_files_after_branch_switch(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Installed post-checkout hook reindexes changed files during branch switches."""
        repo = tmp_path / "repo"
        repo.mkdir()
        fake_home = tmp_path / "home"
        fake_bin = fake_home / ".gobby" / "bin"
        fake_bin.mkdir(parents=True)
        gcode_fifo = tmp_path / "gcode.fifo"
        os.mkfifo(gcode_fifo)
        gcode = fake_bin / "gcode"
        gcode.write_text(
            f"#!/usr/bin/env bash\nprintf '%s\\n' \"$@\" > {shlex.quote(str(gcode_fifo))}\nexit 0\n"
        )
        gcode.chmod(gcode.stat().st_mode | stat.S_IXUSR)
        monkeypatch.setenv("HOME", str(fake_home))

        self._git(repo, "init")
        self._git(repo, "checkout", "-b", "main")
        self._git(repo, "config", "user.email", "test@example.com")
        self._git(repo, "config", "user.name", "Test User")
        (repo / "tracked.txt").write_text("main\n")
        self._git(repo, "add", "tracked.txt")
        self._git(repo, "commit", "-m", "initial")

        self._git(repo, "checkout", "-b", "feature")
        (repo / "tracked.txt").write_text("feature\n")
        (repo / "branch-only.txt").write_text("feature\n")
        self._git(repo, "add", "tracked.txt", "branch-only.txt")
        self._git(repo, "commit", "-m", "feature")
        self._git(repo, "checkout", "main")

        result = install_git_hooks(repo)
        assert result["success"] is True

        reader = subprocess.Popen(
            ["cat", str(gcode_fifo)],
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
        )
        try:
            self._git(repo, "checkout", "feature")
            stdout, _ = reader.communicate(timeout=3)
        except subprocess.TimeoutExpired:
            reader.kill()
            reader.communicate()
            pytest.fail("post-checkout hook did not reindex branch-only.txt")

        assert "branch-only.txt" in stdout

    def test_post_commit_lock_busy_exits_without_codewiki_refresh(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        repo = tmp_path / "repo"
        repo.mkdir()
        fake_home = tmp_path / "home"
        gobby_bin = fake_home / ".gobby" / "bin"
        path_bin = fake_home / "bin"
        gobby_bin.mkdir(parents=True)
        path_bin.mkdir()
        args_file = tmp_path / "gcode.args"
        done_fifo = tmp_path / "gcode.done.fifo"
        os.mkfifo(done_fifo)
        waiter_file = tmp_path / "gcode.waiter"
        curl_file = tmp_path / "curl.called"
        gcode = gobby_bin / "gcode"
        gcode.write_text(
            "#!/usr/bin/env bash\n"
            f"printf '%s\\n' \"$@\" > {shlex.quote(str(args_file))}\n"
            'for ARG in "$@"; do\n'
            '  if [ "$ARG" = "--skip-if-locked" ]; then\n'
            f"    printf 'done\\n' > {shlex.quote(str(done_fifo))}\n"
            "    exit 3\n"
            "  fi\n"
            "done\n"
            f"touch {shlex.quote(str(waiter_file))}\n"
            "sleep 5\n"
        )
        gcode.chmod(gcode.stat().st_mode | stat.S_IXUSR)
        curl = path_bin / "curl"
        curl.write_text(f"#!/usr/bin/env bash\ntouch {shlex.quote(str(curl_file))}\n")
        curl.chmod(curl.stat().st_mode | stat.S_IXUSR)
        monkeypatch.setenv("HOME", str(fake_home))
        monkeypatch.setenv("PATH", f"{path_bin}{os.pathsep}{os.environ['PATH']}")

        self._git(repo, "init")
        self._git(repo, "config", "user.email", "test@example.com")
        self._git(repo, "config", "user.name", "Test User")
        (repo / "tracked.txt").write_text("content\n")
        self._git(repo, "add", "tracked.txt")
        self._git(repo, "commit", "-m", "initial")
        (repo / "tracked.txt").write_text("updated\n")
        self._git(repo, "add", "tracked.txt")
        self._git(repo, "commit", "-m", "update")
        result = install_git_hooks(repo)
        assert result["success"] is True

        hook = repo / ".git" / "hooks" / "post-commit"
        reader = subprocess.Popen(
            ["cat", str(done_fifo)],
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
        )
        try:
            subprocess.run([str(hook)], cwd=repo, check=False, timeout=1)
            stdout, _ = reader.communicate(timeout=1)
        except subprocess.TimeoutExpired:
            reader.kill()
            reader.communicate()
            pytest.fail("post-commit gcode process did not exit after lock skip")

        assert stdout == "done\n"
        assert "--skip-if-locked" in args_file.read_text().splitlines()
        assert not waiter_file.exists()
        assert not curl_file.exists()

    @staticmethod
    def _git(repo: Path, *args: str) -> None:
        subprocess.run(
            ["git", *args],
            cwd=repo,
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )


class TestUninstallGitHooks:
    """Tests for uninstall_git_hooks function."""

    def test_fails_if_not_git_repository(self, tmp_path: Path) -> None:
        """Test that uninstallation fails if not in a git repository."""
        result = uninstall_git_hooks(tmp_path)

        assert result["success"] is False
        assert "Not a git repository" in result["error"]

    def test_succeeds_if_no_hooks_directory(self, tmp_path: Path) -> None:
        """Test that uninstallation succeeds if no hooks directory exists."""
        git_dir = tmp_path / ".git"
        git_dir.mkdir()

        result = uninstall_git_hooks(tmp_path)

        assert result["success"] is True

    def test_uninstall_uses_common_hooks_dir_for_linked_worktree(self, tmp_path: Path) -> None:
        """Test that linked worktree uninstall reads hooks from the common Git dir."""
        worktree = tmp_path / "worktree"
        git_dir = tmp_path / "main" / ".git" / "worktrees" / "worktree"
        worktree.mkdir()
        git_dir.mkdir(parents=True)
        (worktree / ".git").write_text(f"gitdir: {git_dir}\n", encoding="utf-8")
        (git_dir / "commondir").write_text("../..\n", encoding="utf-8")
        install_git_hooks(worktree)

        result = uninstall_git_hooks(worktree)

        assert result["success"] is True
        assert set(result["removed"]) == set(HOOK_TEMPLATES.keys())

    def test_removes_gobby_section_from_hooks(self, tmp_path: Path) -> None:
        """Test that Gobby sections are removed from hooks."""
        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        # Install hooks first
        install_git_hooks(tmp_path)

        # Uninstall
        result = uninstall_git_hooks(tmp_path)

        assert result["success"] is True
        assert set(result["removed"]) == set(HOOK_TEMPLATES.keys())

    def test_preserves_other_hook_content(self, tmp_path: Path) -> None:
        """Test that non-Gobby hook content is preserved."""
        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        # Create hook with existing content
        existing_hook = hooks_dir / "pre-commit"
        existing_hook.write_text("#!/bin/bash\necho 'existing'\n")

        # Install Gobby hooks
        install_git_hooks(tmp_path)

        # Verify combined content
        content_before = existing_hook.read_text()
        assert "existing" in content_before
        assert GOBBY_HOOK_START in content_before

        # Uninstall
        result = uninstall_git_hooks(tmp_path)

        assert result["success"] is True

        content_after = existing_hook.read_text()
        assert "existing" in content_after
        assert GOBBY_HOOK_START not in content_after

    def test_removes_gobby_content_leaves_shebang(self, tmp_path: Path) -> None:
        """Test that hooks with only Gobby content have Gobby removed but shebang retained."""
        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        # Install hooks (creates hooks with shebang + Gobby content)
        install_git_hooks(tmp_path)

        # Verify hooks exist
        for hook_name in HOOK_TEMPLATES:
            assert (hooks_dir / hook_name).exists()

        # Uninstall
        uninstall_git_hooks(tmp_path)

        # Hooks should still exist but only contain shebang (non-empty content)
        for hook_name in HOOK_TEMPLATES:
            hook_path = hooks_dir / hook_name
            assert hook_path.exists()
            content = hook_path.read_text()
            assert GOBBY_HOOK_START not in content
            assert content.strip() == "#!/usr/bin/env bash"

    def test_reports_not_found_hooks(self, tmp_path: Path) -> None:
        """Test that non-existent hooks are reported as not found."""
        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        result = uninstall_git_hooks(tmp_path)

        assert result["success"] is True
        assert set(result["not_found"]) == set(HOOK_TEMPLATES.keys())

    def test_removes_hook_file_when_empty_after_uninstall(self, tmp_path: Path) -> None:
        """Test that hook file is deleted when it becomes completely empty."""
        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        # Create a hook file that contains ONLY gobby section (no shebang)
        # This is a contrived case but tests the code path
        hook_path = hooks_dir / "pre-commit"
        gobby_content = f"{GOBBY_HOOK_START}\n# gobby stuff\n{GOBBY_HOOK_END}\n"
        hook_path.write_text(gobby_content)

        result = uninstall_git_hooks(tmp_path)

        assert result["success"] is True
        assert "pre-commit" in result["removed"]
        # Hook should be deleted since it's now empty
        assert not hook_path.exists()

    def test_reports_hooks_without_gobby_section(self, tmp_path: Path) -> None:
        """Test that hooks without Gobby section are reported as not found."""
        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        # Create hook without Gobby section
        hook = hooks_dir / "pre-commit"
        hook.write_text("#!/bin/bash\necho 'no gobby'\n")

        result = uninstall_git_hooks(tmp_path)

        assert result["success"] is True
        assert "pre-commit" in result["not_found"]


class TestHookTemplates:
    """Tests for HOOK_TEMPLATES constant."""

    def test_all_expected_hooks_defined(self) -> None:
        """Test that all expected hook types are defined."""
        # Updated to include all hooks defined in git_hooks.py
        expected_hooks = {
            "pre-commit",
            "pre-push",
            "pre-merge-commit",
            "post-commit",
            "post-checkout",
            "post-merge",
            "post-rewrite",
        }
        assert set(HOOK_TEMPLATES.keys()) == expected_hooks

    def test_pre_merge_hook_preserves_verification_stderr(self) -> None:
        content = HOOK_TEMPLATES["pre-merge-commit"]

        assert "gobby hooks run pre-merge\n" in content
        assert "gobby hooks run pre-merge 2>/dev/null" not in content

    def test_prepush_template_contains_gobby_backups(self) -> None:
        """Pre-push backs up both artifacts without mutating Git history."""
        content = HOOK_TEMPLATES["pre-push"]
        assert "GOBBY_JSONL_EXPORT_CONTEXT" not in content
        assert "gobby tasks backup --quiet" in content
        assert "gobby memory backup" in content
        assert "commit_jsonl_files" not in content
        assert "git add" not in content
        assert "git commit" not in content
        assert "run git push again to publish it" not in content

        bundled_hook = (
            Path(__file__).resolve().parents[3] / "src" / "gobby" / "hooks" / "git" / "pre-push"
        ).read_text(encoding="utf-8")
        assert "gobby tasks backup --quiet" in bundled_hook
        assert "gobby memory backup" in bundled_hook
        assert "git add" not in bundled_hook
        assert "git commit" not in bundled_hook

    def test_prepush_backup_does_not_commit_or_touch_staging(self, tmp_path: Path) -> None:
        """Local backup refresh leaves HEAD and the caller's staging area unchanged."""
        repo = tmp_path / "repo"
        repo.mkdir()
        subprocess.run(["git", "init", "-b", "main"], cwd=repo, check=True)
        subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=repo, check=True)
        subprocess.run(["git", "config", "user.name", "Test User"], cwd=repo, check=True)

        gobby_dir = repo / ".gobby"
        gobby_dir.mkdir()
        (gobby_dir / "tasks.jsonl").write_text("old task\n")
        (gobby_dir / "memories.jsonl").write_text("old memory\n")
        unrelated = repo / "unrelated.txt"
        unrelated.write_text("original\n")
        subprocess.run(["git", "add", "."], cwd=repo, check=True)
        subprocess.run(["git", "commit", "-m", "initial"], cwd=repo, check=True)

        unrelated.write_text("staged user change\n")
        subprocess.run(["git", "add", "unrelated.txt"], cwd=repo, check=True)

        bin_dir = tmp_path / "bin"
        bin_dir.mkdir()
        fake_gobby = bin_dir / "gobby"
        fake_gobby.write_text(
            "#!/bin/sh\n"
            'if [ "$1 $2" = "tasks backup" ]; then echo "new task" > .gobby/tasks.jsonl; fi\n'
            'if [ "$1 $2" = "memory backup" ]; then echo "new memory" > .gobby/memories.jsonl; fi\n'
        )
        fake_gobby.chmod(0o755)

        hook = repo / "pre-push"
        hook.write_text(HOOK_TEMPLATES["pre-push"])
        head = subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=repo, check=True, capture_output=True, text=True
        ).stdout.strip()
        push_ref = f"refs/heads/main {head} refs/heads/main {'0' * 40}\n"
        env = {
            **{key: value for key, value in os.environ.items() if key != "GOBBY_AGENT_RUN_ID"},
            "PATH": f"{bin_dir}{os.pathsep}{os.environ['PATH']}",
        }

        result = subprocess.run(
            ["bash", str(hook), "origin", "unused"],
            cwd=repo,
            input=push_ref,
            text=True,
            capture_output=True,
            check=True,
            env=env,
        )

        updated_head = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=repo,
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
        staged_files = subprocess.run(
            ["git", "diff", "--cached", "--name-only"],
            cwd=repo,
            check=True,
            capture_output=True,
            text=True,
        ).stdout.splitlines()

        assert updated_head == head
        assert staged_files == ["unrelated.txt"]
        assert (gobby_dir / "tasks.jsonl").read_text() == "new task\n"
        assert (gobby_dir / "memories.jsonl").read_text() == "new memory\n"
        assert "run git push again to publish it" not in result.stderr

    def test_post_commit_template_escapes_nul_delimiter(self, tmp_path: Path) -> None:
        """Generated post-commit hooks must not embed a literal NUL byte."""
        content = HOOK_TEMPLATES["post-commit"]
        assert "\0" not in content
        assert r"tr '\n' '\0'" in content
        assert (
            'xargs -0 "$GCODE" index --quiet --skip-if-locked --files >/dev/null 2>&1'
        ) in content
        assert "/api/code-index/codewiki/refresh" not in content

        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        result = install_git_hooks(tmp_path)

        assert result["success"] is True
        installed = (hooks_dir / "post-commit").read_text()
        assert "\0" not in installed
        assert r"tr '\n' '\0'" in installed
        assert (
            'xargs -0 "$GCODE" index --quiet --skip-if-locked --files >/dev/null 2>&1'
        ) in installed
        assert "/api/code-index/codewiki/refresh" not in installed

    def test_post_history_templates_use_post_commit_reindex_flow(self) -> None:
        """Checkout, merge, and rewrite hooks use the same reindex flow as post-commit."""
        post_commit = HOOK_TEMPLATES["post-commit"]
        shared_snippets = (
            'GCODE="$HOME/.gobby/bin/gcode"',
            r"tr '\n' '\0'",
            'xargs -0 "$GCODE" index --quiet --skip-if-locked --files >/dev/null 2>&1',
        )

        for snippet in shared_snippets:
            assert snippet in post_commit
            for hook_name in ("post-checkout", "post-merge", "post-rewrite"):
                assert snippet in HOOK_TEMPLATES[hook_name]

        for hook_name in ("post-commit", "post-checkout", "post-merge", "post-rewrite"):
            assert "/api/code-index/codewiki/refresh" not in HOOK_TEMPLATES[hook_name]

        checkout = HOOK_TEMPLATES["post-checkout"]
        assert '[ "$3" = "1" ]' in checkout
        assert 'git diff --name-only "$1" "$2"' in checkout

        merge = HOOK_TEMPLATES["post-merge"]
        assert "git diff --name-only ORIG_HEAD HEAD" in merge
        assert "git diff-tree --no-commit-id --name-only -r HEAD" in merge

        rewrite = HOOK_TEMPLATES["post-rewrite"]
        assert "while read -r OLD_REV NEW_REV" in rewrite
        assert 'git diff --name-only "$OLD_REV" "$NEW_REV"' in rewrite

    def test_templates_do_not_restore_jsonl(self) -> None:
        """No installed hook template automatically restores JSONL."""
        for content in HOOK_TEMPLATES.values():
            assert "gobby tasks restore" not in content
            assert "gobby tasks sync --import" not in content
            assert "gobby memory restore" not in content

    def test_post_commit_has_no_codewiki_curl(self, tmp_path: Path) -> None:
        """Fresh post-commit hooks trigger indexing without CodeWiki refresh."""
        content = HOOK_TEMPLATES["post-commit"]
        assert "/api/code-index/codewiki/refresh" not in content

        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir()

        result = install_git_hooks(tmp_path)

        assert result["success"] is True
        installed = (hooks_dir / "post-commit").read_text()
        assert "/api/code-index/codewiki/refresh" not in installed
