"""Compaction and stop lifecycle hook models."""

from typing import Any

from pydantic import Field

from .base import HookInput, HookOutput
from .enums import CompactTrigger


class PreCompactInput(HookInput):
    """
    Input model for pre-compact hook.

    Triggered before context window compaction. Can be used to generate
    summaries or save compaction checkpoints.
    """

    external_id: str = Field(..., min_length=1, description="Unique session identifier")
    transcript_path: str = Field(..., min_length=1, description="Path to conversation transcript")
    trigger: CompactTrigger = Field(
        default=CompactTrigger.AUTO, description="Compaction trigger type"
    )
    custom_instructions: str | None = Field(
        default=None, description="Custom instructions if manually triggered"
    )
    machine_id: str | None = Field(default=None, description="Unique machine identifier")


class PreCompactOutput(HookOutput):
    """
    Output model for pre-compact hook.

    Returns summary data for compaction.
    """

    summary: dict[str, Any] = Field(default_factory=dict, description="Summary data for compaction")


class PostCompactInput(HookInput):
    """Input model for post-compact hook."""

    external_id: str = Field(..., min_length=1, description="Unique session identifier")
    trigger: CompactTrigger = Field(
        default=CompactTrigger.AUTO,
        description="Compaction trigger type",
    )
    compact_summary: str | None = Field(
        default=None,
        description="Summary generated by the compaction operation",
    )
    machine_id: str | None = Field(default=None, description="Unique machine identifier")


class PostCompactOutput(HookOutput):
    """Output model for post-compact hook."""

    pass


class StopInput(HookInput):
    """
    Input model for stop hook.

    Triggered when the main agent stops. Can be used for cleanup and
    final state persistence.
    """

    external_id: str = Field(..., min_length=1, description="Unique session identifier")
    reason: str | None = Field(default=None, description="Reason for stopping")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Additional metadata")
    machine_id: str | None = Field(default=None, description="Unique machine identifier")


class StopOutput(HookOutput):
    """Output model for stop hook."""

    pass  # Uses base HookOutput fields only


class StopFailureInput(HookInput):
    """Input model for stop-failure hook."""

    external_id: str = Field(..., min_length=1, description="Unique session identifier")
    error: str = Field(..., min_length=1, description="Error type for the failed turn")
    error_details: str | None = Field(default=None, description="Additional error details")
    last_assistant_message: str | None = Field(
        default=None,
        description="Rendered API error message shown to the user",
    )
    machine_id: str | None = Field(default=None, description="Unique machine identifier")


class StopFailureOutput(HookOutput):
    """Output model for stop-failure hook."""

    pass
