"""Mappings of HookType -> Pydantic input/output model classes."""

from .agent import (
    SubagentStartInput,
    SubagentStartOutput,
    SubagentStopInput,
    SubagentStopOutput,
    TaskCompletedInput,
    TaskCompletedOutput,
    TaskCreatedInput,
    TaskCreatedOutput,
    TeammateIdleInput,
    TeammateIdleOutput,
)
from .base import HookInput, HookOutput
from .enums import HookType
from .environment import (
    ConfigChangeInput,
    ConfigChangeOutput,
    CwdChangedInput,
    CwdChangedOutput,
    FileChangedInput,
    FileChangedOutput,
    InstructionsLoadedInput,
    InstructionsLoadedOutput,
    NotificationInput,
    NotificationOutput,
    WorktreeCreateInput,
    WorktreeCreateOutput,
    WorktreeRemoveInput,
    WorktreeRemoveOutput,
)
from .interactive import (
    AfterModelInput,
    AfterModelOutput,
    BeforeModelInput,
    BeforeModelOutput,
    ElicitationInput,
    ElicitationOutput,
    ElicitationResultInput,
    ElicitationResultOutput,
    PermissionDeniedInput,
    PermissionDeniedOutput,
    PermissionRequestInput,
    PermissionRequestOutput,
)
from .lifecycle import (
    PostCompactInput,
    PostCompactOutput,
    PreCompactInput,
    PreCompactOutput,
    StopFailureInput,
    StopFailureOutput,
    StopInput,
    StopOutput,
)
from .session import (
    SessionEndInput,
    SessionEndOutput,
    SessionStartInput,
    SessionStartOutput,
    UserPromptSubmitInput,
    UserPromptSubmitOutput,
)
from .tool import (
    PostToolUseFailureInput,
    PostToolUseFailureOutput,
    PostToolUseInput,
    PostToolUseOutput,
    PreToolUseInput,
    PreToolUseOutput,
)

HOOK_INPUT_MODELS: dict[HookType, type[HookInput]] = {
    HookType.SESSION_START: SessionStartInput,
    HookType.SESSION_END: SessionEndInput,
    HookType.USER_PROMPT_SUBMIT: UserPromptSubmitInput,
    HookType.PRE_TOOL_USE: PreToolUseInput,
    HookType.POST_TOOL_USE: PostToolUseInput,
    HookType.POST_TOOL_USE_FAILURE: PostToolUseFailureInput,
    HookType.PRE_COMPACT: PreCompactInput,
    HookType.POST_COMPACT: PostCompactInput,
    HookType.STOP: StopInput,
    HookType.STOP_FAILURE: StopFailureInput,
    HookType.SUBAGENT_START: SubagentStartInput,
    HookType.SUBAGENT_STOP: SubagentStopInput,
    HookType.TASK_CREATED: TaskCreatedInput,
    HookType.TASK_COMPLETED: TaskCompletedInput,
    HookType.TEAMMATE_IDLE: TeammateIdleInput,
    HookType.NOTIFICATION: NotificationInput,
    HookType.INSTRUCTIONS_LOADED: InstructionsLoadedInput,
    HookType.CONFIG_CHANGE: ConfigChangeInput,
    HookType.CWD_CHANGED: CwdChangedInput,
    HookType.FILE_CHANGED: FileChangedInput,
    HookType.WORKTREE_CREATE: WorktreeCreateInput,
    HookType.WORKTREE_REMOVE: WorktreeRemoveInput,
    HookType.ELICITATION: ElicitationInput,
    HookType.ELICITATION_RESULT: ElicitationResultInput,
    HookType.BEFORE_MODEL: BeforeModelInput,
    HookType.AFTER_MODEL: AfterModelInput,
    HookType.PERMISSION_REQUEST: PermissionRequestInput,
    HookType.PERMISSION_DENIED: PermissionDeniedInput,
}

HOOK_OUTPUT_MODELS: dict[HookType, type[HookOutput]] = {
    HookType.SESSION_START: SessionStartOutput,
    HookType.SESSION_END: SessionEndOutput,
    HookType.USER_PROMPT_SUBMIT: UserPromptSubmitOutput,
    HookType.PRE_TOOL_USE: PreToolUseOutput,
    HookType.POST_TOOL_USE: PostToolUseOutput,
    HookType.POST_TOOL_USE_FAILURE: PostToolUseFailureOutput,
    HookType.PRE_COMPACT: PreCompactOutput,
    HookType.POST_COMPACT: PostCompactOutput,
    HookType.STOP: StopOutput,
    HookType.STOP_FAILURE: StopFailureOutput,
    HookType.SUBAGENT_START: SubagentStartOutput,
    HookType.SUBAGENT_STOP: SubagentStopOutput,
    HookType.TASK_CREATED: TaskCreatedOutput,
    HookType.TASK_COMPLETED: TaskCompletedOutput,
    HookType.TEAMMATE_IDLE: TeammateIdleOutput,
    HookType.NOTIFICATION: NotificationOutput,
    HookType.INSTRUCTIONS_LOADED: InstructionsLoadedOutput,
    HookType.CONFIG_CHANGE: ConfigChangeOutput,
    HookType.CWD_CHANGED: CwdChangedOutput,
    HookType.FILE_CHANGED: FileChangedOutput,
    HookType.WORKTREE_CREATE: WorktreeCreateOutput,
    HookType.WORKTREE_REMOVE: WorktreeRemoveOutput,
    HookType.ELICITATION: ElicitationOutput,
    HookType.ELICITATION_RESULT: ElicitationResultOutput,
    HookType.BEFORE_MODEL: BeforeModelOutput,
    HookType.AFTER_MODEL: AfterModelOutput,
    HookType.PERMISSION_REQUEST: PermissionRequestOutput,
    HookType.PERMISSION_DENIED: PermissionDeniedOutput,
}
