use std::collections::BTreeMap;

pub(super) const GCORE_CODE_INDEX_TABLES: [&str; 9] = [
    "code_calls",
    "code_content_chunks",
    "code_imports",
    "code_indexed_file_states",
    "code_indexed_files",
    "code_indexed_project_states",
    "code_indexed_projects",
    "code_inheritance",
    "code_symbols",
];

pub(super) const GCORE_CODE_INDEX_CORE_TABLES: [&str; 8] = [
    "code_calls",
    "code_content_chunks",
    "code_imports",
    "code_indexed_file_states",
    "code_indexed_files",
    "code_indexed_project_states",
    "code_indexed_projects",
    "code_symbols",
];

pub(super) fn adopted_column_contracts() -> BTreeMap<&'static str, &'static [&'static str]> {
    BTreeMap::from([
        (
            "code_indexed_projects",
            &["id", "created_at", "updated_at"] as &[_],
        ),
        (
            "code_indexed_project_states",
            &[
                "machine_id",
                "project_id",
                "root_path",
                "total_files",
                "total_symbols",
                "last_indexed_at",
                "index_duration_ms",
                "created_at",
                "updated_at",
            ] as &[_],
        ),
        (
            "code_indexed_file_states",
            &[
                "machine_id",
                "project_id",
                "file_path",
                "content_hash",
                "updated_at",
            ] as &[_],
        ),
        (
            "code_indexed_files",
            &[
                "id",
                "project_id",
                "file_path",
                "language",
                "content_hash",
                "symbol_count",
                "byte_size",
                "graph_synced",
                "vectors_synced",
                "graph_sync_attempted_at",
                "vector_sync_attempted_at",
                "indexed_at",
            ] as &[_],
        ),
        (
            "code_symbols",
            &[
                "id",
                "project_id",
                "file_path",
                "name",
                "qualified_name",
                "kind",
                "language",
                "byte_start",
                "byte_end",
                "line_start",
                "line_end",
                "signature",
                "docstring",
                "parent_symbol_id",
                "content_hash",
                "summary",
                "summary_attempted_at",
                "created_at",
                "updated_at",
            ] as &[_],
        ),
        (
            "code_imports",
            &["id", "project_id", "source_file", "target_module"] as &[_],
        ),
        (
            "code_calls",
            &[
                "id",
                "project_id",
                "caller_symbol_id",
                "callee_symbol_id",
                "callee_name",
                "callee_target_kind",
                "callee_external_module",
                "file_path",
                "line",
            ] as &[_],
        ),
        (
            "code_inheritance",
            &[
                "id",
                "project_id",
                "source_symbol_id",
                "source_name",
                "source_kind",
                "source_external_module",
                "target_symbol_id",
                "target_name",
                "target_kind",
                "target_external_module",
                "heritage_kind",
                "file_path",
                "content_hash",
                "line",
            ] as &[_],
        ),
        (
            "code_content_chunks",
            &[
                "id",
                "project_id",
                "file_path",
                "chunk_index",
                "line_start",
                "line_end",
                "content",
                "language",
                "created_at",
            ] as &[_],
        ),
        ("gwiki_documents", &["id"] as &[_]),
        ("gwiki_chunks", &["id", "document_id"] as &[_]),
        ("gwiki_sources", &["id"] as &[_]),
    ])
}
