[workspace]
members = ["crates/gcode", "crates/gcore", "crates/gdaemon", "crates/ghook", "crates/gterminal", "crates/gwiki"]
resolver = "3"

[profile.release]
lto = true
strip = true

[profile.release.package.gobby-code]
opt-level = 3

[profile.release.package.gobby-daemon]
opt-level = 3

[profile.release.package.gobby-hooks]
opt-level = "z"

[profile.release.package.gobby-wiki]
opt-level = 3

[patch.crates-io]
portable-pty = { path = "crates/gterminal/vendor/portable-pty" }
