// Generated by scripts/generate_runtime_config_contract.py — do not edit.
// Shared dynamic-segment codec vectors from gobby.config.registry; the
// checked-in copy is byte-compared against fresh registry output in
// tests/config/test_runtime_config_contract.py.

export const DYNAMIC_SEGMENT_CODEC_VECTORS: ReadonlyArray<{
  readonly decoded: string
  readonly encoded: string
}> = [
  { decoded: "plain", encoded: "plain" },
  { decoded: "AZaz09-_~", encoded: "AZaz09-_~" },
  { decoded: "dot.segment", encoded: "dot%2Esegment" },
  { decoded: "percent%sign", encoded: "percent%25sign" },
  { decoded: "already%2Eencoded", encoded: "already%252Eencoded" },
  { decoded: "slash/value", encoded: "slash%2Fvalue" },
  { decoded: "space value", encoded: "space%20value" },
  { decoded: "child.looking", encoded: "child%2Elooking" },
  { decoded: "café", encoded: "caf%C3%A9" },
  { decoded: "配置", encoded: "%E9%85%8D%E7%BD%AE" },
  { decoded: "🙂", encoded: "%F0%9F%99%82" },
  { decoded: "é", encoded: "%C3%A9" },
  { decoded: "é", encoded: "e%CC%81" },
]

export const INVALID_DYNAMIC_SEGMENTS: readonly string[] = [
  "",
  "%",
  "%2",
  "%GG",
  "%2e",
  "%41",
  "%7E",
  "raw.dot",
  "raw space",
  "bad+plus",
  "bad=equals",
  "%C0%AF",
  "%E0%80%AF",
  "%ED%A0%80",
  "é",
  "%FF",
]
