import { useMemo, useState } from 'react'
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogTitle,
} from './ui/Dialog'
import { Button } from './ui/Button'

interface ToolResultImageProps {
  src: string
}

function extensionFromImageSrc(src: string): string {
  const dataMatch = /^data:image\/([^;,]+)/i.exec(src)
  if (dataMatch) {
    const mimeSubtype = dataMatch[1].toLowerCase()
    if (mimeSubtype === 'jpeg') return 'jpg'
    if (mimeSubtype === 'svg+xml') return 'svg'
    return mimeSubtype.replace(/[^a-z0-9]/g, '') || 'png'
  }

  try {
    const pathname = new URL(src, window.location.origin).pathname
    const pathMatch = /\.([a-z0-9]+)$/i.exec(pathname)
    return pathMatch?.[1]?.toLowerCase() || 'png'
  } catch {
    return 'png'
  }
}

export function ToolResultImage({ src }: ToolResultImageProps) {
  const [open, setOpen] = useState(false)
  const [fitToScreen, setFitToScreen] = useState(true)
  const downloadName = useMemo(
    () => `tool-result-image.${extensionFromImageSrc(src)}`,
    [src],
  )

  return (
    <>
      <div className="flex w-full justify-center py-2">
        <button
          type="button"
          className="group max-w-full cursor-zoom-in rounded-lg border border-border bg-muted/20 p-1 transition-colors hover:bg-muted/40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent focus-visible:ring-offset-2 focus-visible:ring-offset-background"
          onClick={() => {
            setFitToScreen(true)
            setOpen(true)
          }}
          aria-label="Open full-size tool result image"
        >
          <img
            src={src}
            alt="Tool result image"
            className="block max-h-96 max-w-full rounded-md object-contain"
          />
        </button>
      </div>

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="flex h-[calc(100dvh-1rem)] w-[calc(100vw-1rem)] max-w-none flex-col gap-0 overflow-hidden rounded-lg p-0 sm:h-[calc(100vh-3rem)] sm:w-[calc(100vw-3rem)]">
          <div className="flex flex-wrap items-center justify-between gap-2 border-b border-border px-3 py-2">
            <div className="min-w-0">
              <DialogTitle className="text-sm font-medium">
                Tool result image
              </DialogTitle>
              <DialogDescription className="sr-only">
                Preview, open, or download the full image generated by the tool.
              </DialogDescription>
            </div>
            <div className="flex flex-wrap items-center justify-end gap-2">
              <div className="inline-flex rounded-md border border-border p-0.5">
                <Button
                  type="button"
                  size="sm"
                  variant={fitToScreen ? 'default' : 'ghost'}
                  className="h-7 px-2"
                  onClick={() => setFitToScreen(true)}
                >
                  Fit
                </Button>
                <Button
                  type="button"
                  size="sm"
                  variant={fitToScreen ? 'ghost' : 'default'}
                  className="h-7 px-2"
                  onClick={() => setFitToScreen(false)}
                >
                  100%
                </Button>
              </div>
              <Button asChild size="sm" variant="outline" className="h-8 px-2">
                <a href={src} target="_blank" rel="noreferrer">
                  Open
                </a>
              </Button>
              <Button asChild size="sm" variant="outline" className="h-8 px-2">
                <a href={src} download={downloadName}>
                  Download
                </a>
              </Button>
              <DialogClose asChild>
                <Button type="button" size="sm" variant="ghost" className="h-8 px-2">
                  Close
                </Button>
              </DialogClose>
            </div>
          </div>

          <div className="flex min-h-0 flex-1 items-center justify-center overflow-auto bg-black/90 p-3 sm:p-6">
            <img
              src={src}
              alt="Full-size tool result image"
              className={
                fitToScreen
                  ? 'max-h-full max-w-full object-contain'
                  : 'max-h-none max-w-none object-contain'
              }
            />
          </div>
        </DialogContent>
      </Dialog>
    </>
  )
}
