"""Daemon-owned AI capability registry."""

from gobby.ai.audio import (
    AudioCapabilityAdapter,
    AudioCapabilityOutput,
    AudioCapabilityRequest,
    AudioCapabilityResult,
    AudioCapabilityService,
    AudioProviderUnavailableError,
    AudioSegment,
    OpenAICompatibleAudioAdapter,
    WhisperAudioAdapter,
    build_daemon_audio_service,
)
from gobby.ai.registry import (
    CANONICAL_AI_CAPABILITIES,
    AIAdapterStyle,
    AICapability,
    AICapabilityRegistry,
    CapabilityBinding,
    CapabilityStatus,
    CapabilityUnavailableError,
    build_daemon_ai_capability_registry,
    normalize_capability,
)
from gobby.ai.text_generation import (
    ACPTextGenerateAdapter,
    CodexAppServerTextGenerateAdapter,
    DroidCLITextGenerateAdapter,
    LLMProviderTextGenerateAdapter,
    TextGenerateAdapter,
    TextGenerationRequest,
    TextGenerationService,
    build_daemon_text_generation_service,
)
from gobby.ai.vision import (
    LLMProviderVisionExtractAdapter,
    VisionExtractAdapter,
    VisionExtractRequest,
    VisionExtractResult,
    VisionExtractService,
    build_daemon_vision_extract_service,
)

__all__ = [
    "ACPTextGenerateAdapter",
    "AudioCapabilityAdapter",
    "AudioCapabilityOutput",
    "AudioCapabilityRequest",
    "AudioCapabilityResult",
    "AudioCapabilityService",
    "AudioProviderUnavailableError",
    "AudioSegment",
    "AIAdapterStyle",
    "AICapability",
    "AICapabilityRegistry",
    "CANONICAL_AI_CAPABILITIES",
    "CapabilityBinding",
    "CapabilityStatus",
    "CapabilityUnavailableError",
    "CodexAppServerTextGenerateAdapter",
    "DroidCLITextGenerateAdapter",
    "LLMProviderTextGenerateAdapter",
    "LLMProviderVisionExtractAdapter",
    "OpenAICompatibleAudioAdapter",
    "TextGenerateAdapter",
    "TextGenerationRequest",
    "TextGenerationService",
    "VisionExtractAdapter",
    "VisionExtractRequest",
    "VisionExtractResult",
    "VisionExtractService",
    "WhisperAudioAdapter",
    "build_daemon_ai_capability_registry",
    "build_daemon_audio_service",
    "build_daemon_text_generation_service",
    "build_daemon_vision_extract_service",
    "normalize_capability",
]
