"""Daemon-owned AI capability registry."""

from gobby.ai.audio import (
    AudioCapabilityAdapter,
    AudioCapabilityOutput,
    AudioCapabilityRequest,
    AudioCapabilityResult,
    AudioCapabilityService,
    AudioProviderUnavailableError,
    AudioSegment,
    OpenAICompatibleAudioAdapter,
    WhisperAudioAdapter,
    build_daemon_audio_service,
)
from gobby.ai.embeddings import EmbeddingGenerationError, EmbeddingService
from gobby.ai.registry import (
    CANONICAL_AI_CAPABILITIES,
    AIAdapterStyle,
    AICapability,
    AICapabilityRegistry,
    CapabilityBinding,
    CapabilityStatus,
    CapabilityUnavailableError,
    build_daemon_ai_capability_registry,
    normalize_capability,
)
from gobby.ai.text_generation import (
    AgyCLITextGenerateAdapter,
    ClaudeTextGenerateAdapter,
    CodexCLITextGenerateAdapter,
    DroidCLITextGenerateAdapter,
    LocalTextGenerateAdapter,
    TextGenerateAdapter,
    TextGenerationRequest,
    TextGenerationService,
    build_daemon_text_generation_service,
)
from gobby.ai.tool_chat import (
    ToolChatRequest,
    ToolChatResult,
    ToolChatService,
    ToolLoopLimits,
    ToolPolicy,
    build_daemon_tool_chat_service,
)
from gobby.ai.vision import (
    ClaudeVisionExtractAdapter,
    LocalVisionExtractAdapter,
    VisionExtractAdapter,
    VisionExtractRequest,
    VisionExtractResult,
    VisionExtractService,
    build_daemon_vision_extract_service,
)

__all__ = [
    "AudioCapabilityAdapter",
    "AudioCapabilityOutput",
    "AudioCapabilityRequest",
    "AudioCapabilityResult",
    "AudioCapabilityService",
    "AudioProviderUnavailableError",
    "AudioSegment",
    "AIAdapterStyle",
    "AICapability",
    "AICapabilityRegistry",
    "AgyCLITextGenerateAdapter",
    "CANONICAL_AI_CAPABILITIES",
    "CapabilityBinding",
    "CapabilityStatus",
    "CapabilityUnavailableError",
    "ClaudeTextGenerateAdapter",
    "ClaudeVisionExtractAdapter",
    "CodexCLITextGenerateAdapter",
    "DroidCLITextGenerateAdapter",
    "EmbeddingGenerationError",
    "EmbeddingService",
    "LocalTextGenerateAdapter",
    "LocalVisionExtractAdapter",
    "OpenAICompatibleAudioAdapter",
    "TextGenerateAdapter",
    "TextGenerationRequest",
    "TextGenerationService",
    "ToolChatRequest",
    "ToolChatResult",
    "ToolChatService",
    "ToolLoopLimits",
    "ToolPolicy",
    "VisionExtractAdapter",
    "VisionExtractRequest",
    "VisionExtractResult",
    "VisionExtractService",
    "WhisperAudioAdapter",
    "build_daemon_ai_capability_registry",
    "build_daemon_audio_service",
    "build_daemon_text_generation_service",
    "build_daemon_tool_chat_service",
    "build_daemon_vision_extract_service",
    "normalize_capability",
]
