#!/usr/bin/env python3
"""Flatten the embedded gcore schema assets into one numbered baseline.

The new ``baseline.sql`` is the exact statement sequence a fresh apply runs
today: the current baseline followed by every pending numbered migration in
version order. Fresh lineages receipt-stamp ``-- gobby:destructive``
migrations without executing them, so their bodies are omitted. Two rewrites
keep the rest valid inside the baseline's single transaction:
``CREATE INDEX CONCURRENTLY`` becomes ``CREATE INDEX`` and ``-- gobby:``
directive lines are dropped (directives only gate numbered migrations).
Everything else is byte-preserved; ``scripts/verify_flatten.py`` proves the
result against the previous binary.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from dataclasses import dataclass
from pathlib import Path

DEFAULT_SCHEMA_DIR = Path("crates/gcore/assets/schema")
DEFAULT_VERSION = 419
GENERATED_HEADER = "-- Generated by scripts/flatten_schema.py. Do not edit by hand."
_MIGRATION_NAME = re.compile(r"^(\d+)_.+\.sql$")
_CONCURRENTLY = re.compile(r"\bCONCURRENTLY\s+")
_DIRECTIVE_PREFIX = "-- gobby:"
_DESTRUCTIVE_DIRECTIVE = "-- gobby:destructive"


@dataclass(frozen=True)
class Migration:
    version: int
    path: Path


def migrations_in(schema_dir: Path) -> list[Migration]:
    """Return the numbered migrations in version order, requiring contiguity."""
    found: list[Migration] = []
    for path in sorted((schema_dir / "migrations").glob("*.sql")):
        match = _MIGRATION_NAME.match(path.name)
        if match is None:
            raise ValueError(f"unexpected migration file name: {path.name}")
        found.append(Migration(int(match.group(1)), path))
    found.sort(key=lambda migration: migration.version)
    for previous, current in zip(found, found[1:], strict=False):
        if current.version != previous.version + 1:
            raise ValueError(
                f"migrations are not contiguous: {previous.path.name} -> {current.path.name}"
            )
    return found


def is_destructive(sql: str) -> bool:
    return any(line.startswith(_DESTRUCTIVE_DIRECTIVE) for line in sql.splitlines())


def rewrite(sql: str) -> str:
    """Drop directive lines and make concurrent index builds transactional."""
    kept = [line for line in sql.splitlines() if not line.startswith(_DIRECTIVE_PREFIX)]
    return _CONCURRENTLY.sub("", "\n".join(kept).strip("\n")) + "\n"


def assemble(
    baseline_sql: str,
    migrations: list[tuple[str, str]],
    *,
    version: int,
    from_version: int,
) -> str:
    """Build the flattened baseline from the old baseline and (name, sql) migrations."""
    body = baseline_sql
    if body.startswith(GENERATED_HEADER):
        body = body.partition("\n")[2]
    last = from_version + len(migrations)
    provenance = f"baseline@{from_version} + migrations {from_version + 1}-{last}"
    parts = [
        f"{GENERATED_HEADER}\n",
        f"-- baseline@{version}: flattened from {provenance}.\n",
        "\n",
        rewrite(body),
    ]
    for name, sql in migrations:
        if is_destructive(sql):
            parts.append(
                f"\n-- flattened migration {name}: destructive; fresh lineages "
                "receipt-stamp it without executing.\n"
            )
            continue
        parts.append(f"\n-- flattened migration {name}\n")
        parts.append(rewrite(sql))
    return "".join(parts)


def checksum(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def flatten(schema_dir: Path, *, version: int, write: bool) -> tuple[str, str]:
    """Assemble the flattened baseline; with ``write`` replace it and remove migrations."""
    baseline_path = schema_dir / "baseline.sql"
    migrations = migrations_in(schema_dir)
    if not migrations:
        raise ValueError(f"no migrations to flatten under {schema_dir / 'migrations'}")
    text = assemble(
        baseline_path.read_text(encoding="utf-8"),
        [
            (migration.path.name, migration.path.read_text(encoding="utf-8"))
            for migration in migrations
        ],
        version=version,
        from_version=migrations[0].version - 1,
    )
    digest = checksum(text)
    if write:
        baseline_path.write_text(text, encoding="utf-8")
        for migration in migrations:
            migration.path.unlink()
    return text, digest


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--schema-dir", type=Path, default=DEFAULT_SCHEMA_DIR)
    parser.add_argument(
        "--version",
        type=int,
        default=DEFAULT_VERSION,
        help=f"new baseline version (default: {DEFAULT_VERSION})",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="replace baseline.sql and delete the flattened migration files",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    text, digest = flatten(args.schema_dir, version=args.version, write=args.write)
    mode = "wrote" if args.write else "dry run"
    print(f"{mode} baseline@{args.version} lines={text.count(chr(10))} sha256={digest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
