#!/usr/bin/env python3
"""Regenerate the embedded gcore baseline from a canonical PostgreSQL dump.

The source gdaemon applies baseline@419 to a fresh database on the isolated
test hub. PostgreSQL then emits dependency-ordered DDL for ``public`` and
``gobby_agent_auth``; this script removes dump noise, preserves the role and
login-trigger substrate that schema-scoped pg_dump cannot represent, and
appends deterministically sorted seed inserts. SECURITY DEFINER statements
retain explicit ``public.`` and ``gobby_agent_auth.`` references so gcore can
render each non-public hub into its own application and auth schemas.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib
import json
import os
import re
import subprocess
import sys
import uuid
from collections.abc import Iterator, Mapping
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import psycopg
from psycopg import sql
from psycopg.conninfo import conninfo_to_dict, make_conninfo

from gobby.storage.schema_contract import DATABASE_URL_ENV, EXPECTED_IDENTITY_ENV

if __package__:
    from scripts.schema_diff import (
        SEED_TABLE_SPECS,
        _dump_schema,
        _postgres_client_connection,
        _run_postgres_client,
        _split_sql_statements,
        _split_top_level_commas,
        normalize_schema_dump,
    )
else:
    _schema_diff = importlib.import_module("schema_diff")
    SEED_TABLE_SPECS = _schema_diff.SEED_TABLE_SPECS
    _dump_schema = _schema_diff._dump_schema
    _postgres_client_connection = _schema_diff._postgres_client_connection
    _run_postgres_client = _schema_diff._run_postgres_client
    _split_sql_statements = _schema_diff._split_sql_statements
    _split_top_level_commas = _schema_diff._split_top_level_commas
    normalize_schema_dump = _schema_diff.normalize_schema_dump

DEFAULT_DATABASE_URL = "postgresql://gobby_test:gobby_test@127.0.0.1:60892/gobby_test"
DEFAULT_SCHEMA_DIR = Path("crates/gcore/assets/schema")
DEFAULT_OUTPUT_DIR = Path("docs/evidence/flatten-baseline-420")
DEFAULT_VERSION = 420
GENERATED_HEADER = "-- Generated by scripts/flatten_schema.py. Do not edit by hand."
_APPLICATION_SCHEMA = "public"
_AUTH_SCHEMA = "gobby_agent_auth"
_DUMP_SCHEMAS = (_APPLICATION_SCHEMA, _AUTH_SCHEMA)
_SEED_TABLES = (
    "config_state",
    "projects",
    "sessions",
    "task_stages_registry",
    "task_type_default_stages",
)
_ROLE_PREAMBLE_START = "SELECT pg_advisory_xact_lock("
_ROLE_PREAMBLE_END = "SET check_function_bodies = false;"
_LOGIN_GUARD = "gobby_maintenance_epoch_login_guard"
_GDAEMON_TIMEOUT_SECONDS = 600
_DOLLAR_TAG = re.compile(r"\$[A-Za-z_][A-Za-z0-9_]*\$|\$\$")


@dataclass(frozen=True)
class GeneratedBaseline:
    baseline_sql: str
    normalized_ddl: str
    seed_sql: str
    source_identity: dict[str, Any]


def _strip_dump_noise(dump: str) -> str:
    kept: list[str] = []
    active_tag: str | None = None
    for line in dump.splitlines():
        if active_tag is None and line.lstrip().startswith(("--", "\\restrict", "\\unrestrict")):
            continue
        kept.append(line)
        if active_tag is None:
            match = _DOLLAR_TAG.search(line)
            if match is not None and line.count(match.group(0), match.start()) % 2 == 1:
                active_tag = match.group(0)
        elif line.count(active_tag) % 2 == 1:
            active_tag = None
    return "\n".join(kept)


def _is_schema_creation(statement: str) -> bool:
    compact = re.sub(r"\s+", " ", statement).strip()
    return any(
        re.fullmatch(rf'CREATE SCHEMA (?:"{schema}"|{schema})', compact, re.IGNORECASE) is not None
        for schema in _DUMP_SCHEMAS
    )


def _is_omitted_dump_statement(statement: str) -> bool:
    compact = re.sub(r"\s+", " ", statement).strip()
    upper = compact.upper()
    return (
        not compact
        or upper.startswith("SET ")
        or upper.startswith("SELECT PG_CATALOG.SET_CONFIG(")
        or upper.startswith("CREATE EXTENSION ")
        or upper.startswith("COMMENT ON EXTENSION ")
        or _is_schema_creation(compact)
        or any(
            re.match(
                rf'^COMMENT ON SCHEMA (?:"{schema}"|{schema})\b',
                compact,
                re.IGNORECASE,
            )
            is not None
            for schema in _DUMP_SCHEMAS
        )
        or (
            upper.startswith("ALTER ")
            and " OWNER TO " in upper
            and not upper.endswith(" OWNER TO GOBBY_AGENT_ISSUER")
        )
        or _LOGIN_GUARD in compact
    )


def _unqualify_application_schema(statement: str, application_schema: str) -> str:
    schema = re.escape(application_schema)
    return re.sub(
        rf'(?<![A-Za-z0-9_$])(?:"{schema}"|{schema})\.',
        "",
        statement,
        flags=re.IGNORECASE,
    )


def _requires_explicit_schema_references(statement: str) -> bool:
    upper = statement.upper()
    return "SECURITY DEFINER" in upper or _AUTH_SCHEMA in statement


def render_dump(dump: str, *, application_schema: str) -> str:
    """Render stable executable SQL from dependency-ordered pg_dump output."""
    rendered: list[str] = []
    for raw in _split_sql_statements(_strip_dump_noise(dump)):
        statement = raw.strip()
        if _is_omitted_dump_statement(statement):
            continue
        if re.match(r"CREATE\s+POLICY\s+gobby_migration_owner_access\b", statement, re.I):
            statement = re.sub(
                r'(\bTO\s+)(?:"(?:[^"]|"")*"|[A-Za-z_][A-Za-z0-9_$]*)(?=\s+USING\b)',
                r"\g<1>CURRENT_USER",
                statement,
                count=1,
                flags=re.I,
            )
        if re.match(r"ALTER\s+DEFAULT\s+PRIVILEGES\s+FOR\s+ROLE\b", statement, re.I):
            statement = re.sub(
                r'(\bFOR\s+ROLE\s+)(?:"(?:[^"]|"")*"|[A-Za-z_][A-Za-z0-9_$]*)'
                r"(?=\s+IN\s+SCHEMA\b)",
                r"\g<1>CURRENT_USER",
                statement,
                count=1,
                flags=re.I,
            )
        if not _requires_explicit_schema_references(statement):
            statement = _unqualify_application_schema(statement, application_schema)
        rendered.append(statement + ";")
    return "\n\n".join(rendered) + "\n"


def canonicalize_seed_dump(seed_dump: str) -> str:
    """Return sorted one-row INSERTs with machine timestamps made reproducible."""
    inserts: list[str] = []
    pattern = re.compile(
        r"^INSERT INTO (?:public\.)?(?P<table>[A-Za-z_][A-Za-z0-9_$]*) "
        r"\((?P<columns>.*)\) VALUES \((?P<values>.*)\)$",
        re.DOTALL,
    )
    for statement in _split_sql_statements(_strip_dump_noise(seed_dump)):
        compact = re.sub(r"\s+", " ", statement).strip()
        if not compact.upper().startswith("INSERT INTO "):
            continue
        match = pattern.fullmatch(compact)
        if match is None:
            raise RuntimeError(f"could not canonicalize seed INSERT: {compact[:120]}")
        table = match.group("table")
        if table != "config_state" and table not in SEED_TABLE_SPECS:
            raise RuntimeError(f"seed table has no normalization contract: {table}")
        columns = [item.strip() for item in _split_top_level_commas(match.group("columns"))]
        values = [item.strip() for item in _split_top_level_commas(match.group("values"))]
        if len(columns) != len(values):
            raise RuntimeError(f"seed INSERT column/value mismatch for {table}")
        mutable = (
            frozenset()
            if table == "config_state"
            else SEED_TABLE_SPECS[table].machine_mutable_columns
        )
        values = [
            "NOW()" if column.strip('"') in mutable else value
            for column, value in zip(columns, values, strict=True)
        ]
        inserts.append(f"INSERT INTO {table} ({', '.join(columns)}) VALUES ({', '.join(values)});")
    return "\n\n".join(sorted(inserts)) + ("\n" if inserts else "")


def _role_preamble(source_baseline: str) -> str:
    start = source_baseline.find(_ROLE_PREAMBLE_START)
    end = source_baseline.find(_ROLE_PREAMBLE_END, start)
    if start < 0 or end < 0:
        raise RuntimeError("source baseline role preamble markers are missing")
    end += len(_ROLE_PREAMBLE_END)
    return source_baseline[start:end].strip() + "\n"


def _login_trigger_sql(source_baseline: str) -> str:
    statements = [
        statement.strip() + ";"
        for statement in _split_sql_statements(source_baseline)
        if _LOGIN_GUARD in statement and statement.lstrip().upper().startswith("DO ")
    ]
    if len(statements) != 2 or not any("CREATE EVENT TRIGGER" in item for item in statements):
        raise RuntimeError("source baseline login-trigger rendering contract changed")
    function = f"{_APPLICATION_SCHEMA}.{_LOGIN_GUARD}()"
    statements.extend(
        (
            f"REVOKE ALL ON FUNCTION {function} FROM PUBLIC;",
            f"GRANT ALL ON FUNCTION {function} TO gobby_daemon_runtime;",
        )
    )
    return "\n\n".join(statements) + "\n"


def _pgcrypto_sql(source_baseline: str) -> str:
    statements: list[str] = []
    for raw in _split_sql_statements(source_baseline):
        statement = raw.strip()
        compact = re.sub(r"\s+", " ", statement)
        if re.match(r"CREATE EXTENSION IF NOT EXISTS pgcrypto\b", compact, re.I) or re.match(
            r'GRANT EXECUTE ON FUNCTION (?:(?:"public")|public)\.digest\(BYTEA, TEXT\) '
            r"TO gobby_agent_issuer$",
            compact,
            re.I,
        ):
            statements.append(statement + ";")
    if len(statements) != 2 or not statements[0].upper().startswith("CREATE EXTENSION"):
        raise RuntimeError("source baseline pgcrypto rendering contract changed")
    return "\n\n".join(statements) + "\n"


def assemble_baseline(
    *,
    source_baseline: str,
    schema_dump: str,
    seed_sql: str,
    version: int,
) -> str:
    parts = [
        GENERATED_HEADER,
        f"-- baseline@{version}: canonical pg_dump of baseline@{version - 1}.",
        "",
        _role_preamble(source_baseline).rstrip(),
        "",
        render_dump(schema_dump, application_schema=_APPLICATION_SCHEMA).rstrip(),
        "",
        _pgcrypto_sql(source_baseline).rstrip(),
    ]
    if seed_sql:
        parts.extend(("", seed_sql.rstrip()))
    parts.extend(("", _login_trigger_sql(source_baseline).rstrip(), ""))
    return "\n".join(parts)


def _validate_test_database_url(database_url: str) -> None:
    parameters = conninfo_to_dict(database_url)
    host = str(parameters.get("host", ""))
    port = str(parameters.get("port", ""))
    dbname = str(parameters.get("dbname", ""))
    user = str(parameters.get("user", ""))
    if host not in {"127.0.0.1", "localhost"} or port != "60892":
        raise RuntimeError("flatten_schema requires the isolated PostgreSQL test hub on port 60892")
    if dbname != "gobby_test" or user != "gobby_test":
        raise RuntimeError("flatten_schema requires the isolated gobby_test database and role")


@contextmanager
def scratch_database(database_url: str, label: str) -> Iterator[str]:
    _validate_test_database_url(database_url)
    name = f"gobby_flatten_{label}_{uuid.uuid4().hex[:10]}"
    with psycopg.connect(database_url, autocommit=True) as connection:
        connection.execute(sql.SQL("CREATE DATABASE {}").format(sql.Identifier(name)))
    scratch_url = make_conninfo(database_url, dbname=name)
    try:
        with psycopg.connect(scratch_url, autocommit=True) as connection:
            connection.execute("CREATE EXTENSION IF NOT EXISTS pg_search")
        yield scratch_url
    finally:
        with psycopg.connect(database_url, autocommit=True) as connection:
            connection.execute(
                sql.SQL("DROP DATABASE IF EXISTS {} WITH (FORCE)").format(sql.Identifier(name))
            )


def _run_gdaemon(argv: list[str], *, env: Mapping[str, str], action: str) -> str:
    try:
        result = subprocess.run(  # nosec B603 - fixed binary path and argv, never shell=True
            argv,
            capture_output=True,
            check=False,
            env=env,
            text=True,
            timeout=_GDAEMON_TIMEOUT_SECONDS,
        )
    except subprocess.TimeoutExpired:
        raise RuntimeError(f"{action} timed out after {_GDAEMON_TIMEOUT_SECONDS}s") from None
    except OSError as exc:
        raise RuntimeError(f"{action} failed: {exc}") from exc
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip() or f"exit {result.returncode}"
        raise RuntimeError(f"{action} failed: {detail}")
    return result.stdout


def gdaemon_identity(binary: Path) -> dict[str, Any]:
    output = _run_gdaemon(
        [str(binary), "schema", "version", "--json"],
        env=os.environ,
        action=f"{binary} schema version",
    )
    identity = json.loads(output)
    if not isinstance(identity, dict):
        raise RuntimeError(f"{binary} schema version returned non-object JSON")
    return identity


def _apply_source(binary: Path, database_url: str, identity: dict[str, Any]) -> None:
    env = dict(os.environ)
    env[DATABASE_URL_ENV] = database_url
    env[EXPECTED_IDENTITY_ENV] = json.dumps(identity)
    for action in ("apply", "verify"):
        _run_gdaemon(
            [str(binary), "schema", action],
            env=env,
            action=f"source gdaemon schema {action}",
        )


def _dump_executable_schema(database_url: str, *, pg_dump: str) -> str:
    conninfo, env = _postgres_client_connection(database_url)
    return _run_postgres_client(
        [
            pg_dump,
            "--schema-only",
            *(f"--schema={schema}" for schema in _DUMP_SCHEMAS),
            "--dbname",
            conninfo,
        ],
        action="pg_dump executable schema",
        env=env,
    )


def _dump_seed_rows(database_url: str, *, pg_dump: str) -> str:
    conninfo, env = _postgres_client_connection(database_url)
    table_args = [item for table in _SEED_TABLES for item in ("--table", f"public.{table}")]
    return _run_postgres_client(
        [
            pg_dump,
            "--data-only",
            "--inserts",
            "--column-inserts",
            "--rows-per-insert=1",
            *table_args,
            "--dbname",
            conninfo,
        ],
        action="pg_dump seed rows",
        env=env,
    )


def _normalized_ddl(database_url: str, *, pg_dump: str) -> str:
    sections = []
    for schema in _DUMP_SCHEMAS:
        dump = _dump_schema(database_url, schema, pg_dump=pg_dump)
        normalized = normalize_schema_dump(dump, schema_name=schema)
        sections.append(f"-- {schema}\n{normalized}".rstrip())
    return "\n\n".join(sections) + "\n"


def generate(
    database_url: str,
    *,
    source_gdaemon: Path,
    source_baseline_path: Path,
    version: int,
    pg_dump: str,
) -> GeneratedBaseline:
    identity = gdaemon_identity(source_gdaemon)
    source_version = identity.get("latest_version")
    if source_version != version - 1:
        raise RuntimeError(
            f"source gdaemon latest version is {source_version!r}; expected {version - 1}"
        )
    source_baseline = source_baseline_path.read_text(encoding="utf-8")
    with scratch_database(database_url, "source") as scratch_url:
        _apply_source(source_gdaemon, scratch_url, identity)
        schema_dump = _dump_executable_schema(scratch_url, pg_dump=pg_dump)
        seed_sql = canonicalize_seed_dump(_dump_seed_rows(scratch_url, pg_dump=pg_dump))
        normalized_ddl = _normalized_ddl(scratch_url, pg_dump=pg_dump)
    baseline_sql = assemble_baseline(
        source_baseline=source_baseline,
        schema_dump=schema_dump,
        seed_sql=seed_sql,
        version=version,
    )
    return GeneratedBaseline(
        baseline_sql=baseline_sql,
        normalized_ddl=normalized_ddl,
        seed_sql=seed_sql,
        source_identity=identity,
    )


def _write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)


def _sha256(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def write_generated(
    generated: GeneratedBaseline,
    *,
    baseline_path: Path,
    evidence_dir: Path,
    version: int,
) -> dict[str, Any]:
    manifest: dict[str, Any] = {
        "baseline_path": str(baseline_path),
        "baseline_sha256": _sha256(generated.baseline_sql),
        "baseline_version": version,
        "normalized_ddl_sha256": _sha256(generated.normalized_ddl),
        "seed_sql_sha256": _sha256(generated.seed_sql),
        "source_identity": generated.source_identity,
    }
    _write_atomic(baseline_path, generated.baseline_sql)
    _write_atomic(evidence_dir / "canonical.normalized.sql", generated.normalized_ddl)
    _write_atomic(evidence_dir / "canonical.seeds.sql", generated.seed_sql)
    _write_atomic(
        evidence_dir / "generation.json",
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
    )
    return manifest


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--database-url", default=DEFAULT_DATABASE_URL)
    parser.add_argument(
        "--source-gdaemon",
        type=Path,
        default=Path.home() / ".gobby/bin/gdaemon",
        help="installed gdaemon carrying the source baseline",
    )
    parser.add_argument(
        "--baseline-path",
        type=Path,
        default=DEFAULT_SCHEMA_DIR / "baseline.sql",
    )
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--version", type=int, default=DEFAULT_VERSION)
    parser.add_argument("--pg-dump", default="pg_dump")
    parser.add_argument(
        "--write",
        action="store_true",
        help="replace baseline.sql and write canonical generation evidence",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        generated = generate(
            args.database_url,
            source_gdaemon=args.source_gdaemon,
            source_baseline_path=args.baseline_path,
            version=args.version,
            pg_dump=args.pg_dump,
        )
        digest = _sha256(generated.baseline_sql)
        if args.write:
            write_generated(
                generated,
                baseline_path=args.baseline_path,
                evidence_dir=args.output_dir,
                version=args.version,
            )
        mode = "wrote" if args.write else "dry run"
        print(
            f"{mode} canonical baseline@{args.version} "
            f"lines={generated.baseline_sql.count(chr(10))} sha256={digest}"
        )
        return 0
    except (OSError, RuntimeError, ValueError, json.JSONDecodeError, psycopg.Error) as exc:
        print(f"flatten_schema: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
