#!/usr/bin/env python3
"""Generate the checked-in Rust runtime configuration contract."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, cast

from gobby.config.registry import (
    CONFIG_REGISTRY,
    DYNAMIC_SEGMENT_CODEC_VECTORS,
    INVALID_DYNAMIC_SEGMENTS,
    ConfigVisibility,
)

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
CONTRACT_PATH = (
    REPOSITORY_ROOT / "crates" / "gcore" / "assets" / "config" / "runtime_config_contract.json"
)


def build_contract() -> dict[str, object]:
    """Build the non-restricted registry projection consumed by Rust."""
    public = cast(
        dict[str, dict[str, Any]],
        CONFIG_REGISTRY.json_schema(ConfigVisibility.PUBLIC)["properties"],
    )
    machine = cast(
        dict[str, dict[str, Any]],
        CONFIG_REGISTRY.json_schema(ConfigVisibility.MACHINE)["properties"],
    )
    properties: dict[str, dict[str, Any]] = {**public, **machine}

    exact_keys: list[dict[str, Any]] = []
    patterns: list[dict[str, Any]] = []
    for key in sorted(properties):
        metadata = properties[key]
        entry = dict(metadata)
        if "pattern" in entry:
            patterns.append(entry)
        else:
            exact_keys.append({"key": key, **entry})

    return {
        "version": 1,
        "codec": {
            "safe": "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_~",
            "vectors": [
                {"decoded": decoded, "encoded": encoded}
                for decoded, encoded in DYNAMIC_SEGMENT_CODEC_VECTORS
            ],
            "invalid": list(INVALID_DYNAMIC_SEGMENTS),
        },
        "exactKeys": exact_keys,
        "patterns": patterns,
    }


def render_contract() -> bytes:
    """Serialize the contract with stable key ordering and UTF-8 bytes."""
    rendered = json.dumps(build_contract(), ensure_ascii=False, indent=2, sort_keys=True)
    return f"{rendered}\n".encode()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--stdout", action="store_true", help="write generated bytes to stdout")
    args = parser.parse_args()
    payload = render_contract()
    if args.stdout:
        sys.stdout.buffer.write(payload)
        return
    CONTRACT_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONTRACT_PATH.write_bytes(payload)


if __name__ == "__main__":
    main()
