#!/usr/bin/env python3
"""Generate the checked-in Rust runtime configuration contract."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, cast

from gobby.config.registry import (
    CONFIG_REGISTRY,
    DYNAMIC_SEGMENT_CODEC_VECTORS,
    INVALID_DYNAMIC_SEGMENT_TEXT_VECTORS,
    INVALID_DYNAMIC_SEGMENTS,
    ConfigVisibility,
)

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
CONTRACT_PATH = (
    REPOSITORY_ROOT / "crates" / "gcore" / "assets" / "config" / "runtime_config_contract.json"
)
WEB_VECTORS_PATH = REPOSITORY_ROOT / "web" / "src" / "api" / "runtimeConfigCodecVectors.gen.ts"


def build_contract() -> dict[str, object]:
    """Build the non-restricted registry projection consumed by Rust."""
    public = cast(
        dict[str, dict[str, Any]],
        CONFIG_REGISTRY.json_schema(ConfigVisibility.PUBLIC)["properties"],
    )
    machine = cast(
        dict[str, dict[str, Any]],
        CONFIG_REGISTRY.json_schema(ConfigVisibility.MACHINE)["properties"],
    )
    properties: dict[str, dict[str, Any]] = {**public, **machine}

    exact_keys: list[dict[str, Any]] = []
    patterns: list[dict[str, Any]] = []
    for key in sorted(properties):
        metadata = properties[key]
        entry = dict(metadata)
        if "pattern" in entry:
            patterns.append(entry)
        else:
            exact_keys.append({"key": key, **entry})

    return {
        "version": 1,
        "codec": {
            "safe": "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_~",
            "vectors": [
                {"decoded": decoded, "encoded": encoded}
                for decoded, encoded in DYNAMIC_SEGMENT_CODEC_VECTORS
            ],
            "invalid": list(INVALID_DYNAMIC_SEGMENTS),
        },
        "exactKeys": exact_keys,
        "patterns": patterns,
    }


def render_contract() -> bytes:
    """Serialize the contract with stable key ordering and UTF-8 bytes."""
    rendered = json.dumps(build_contract(), ensure_ascii=False, indent=2, sort_keys=True)
    return f"{rendered}\n".encode()


def render_web_vectors() -> bytes:
    """Render the shared codec vectors as a generated TypeScript fixture."""

    def literal(value: str) -> str:
        return json.dumps(value, ensure_ascii=False)

    def invalid_text_literal(value: str) -> str:
        return json.dumps(value, ensure_ascii=True)

    lines = [
        "// Generated by scripts/generate_runtime_config_contract.py — do not edit.",
        "// Shared dynamic-segment codec vectors from gobby.config.registry; the",
        "// checked-in copy is byte-compared against fresh registry output in",
        "// tests/config/test_runtime_config_contract.py.",
        "",
        "export const DYNAMIC_SEGMENT_CODEC_VECTORS: ReadonlyArray<{",
        "  readonly decoded: string",
        "  readonly encoded: string",
        "}> = [",
        *(
            f"  {{ decoded: {literal(decoded)}, encoded: {literal(encoded)} }},"
            for decoded, encoded in DYNAMIC_SEGMENT_CODEC_VECTORS
        ),
        "]",
        "",
        "export const INVALID_DYNAMIC_SEGMENTS: readonly string[] = [",
        *(f"  {literal(segment)}," for segment in INVALID_DYNAMIC_SEGMENTS),
        "]",
        "",
        "export const INVALID_DYNAMIC_SEGMENT_TEXT_VECTORS: readonly string[] = [",
        *(
            f"  {invalid_text_literal(segment)},"
            for segment in INVALID_DYNAMIC_SEGMENT_TEXT_VECTORS
        ),
        "]",
    ]
    return "".join(f"{line}\n" for line in lines).encode()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--stdout", action="store_true", help="write generated bytes to stdout")
    parser.add_argument(
        "--stdout-web",
        action="store_true",
        help="write the generated web codec-vector fixture to stdout",
    )
    args = parser.parse_args()
    if args.stdout and args.stdout_web:
        parser.error("--stdout and --stdout-web are mutually exclusive")
    if args.stdout:
        sys.stdout.buffer.write(render_contract())
        return
    if args.stdout_web:
        sys.stdout.buffer.write(render_web_vectors())
        return
    CONTRACT_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONTRACT_PATH.write_bytes(render_contract())
    WEB_VECTORS_PATH.parent.mkdir(parents=True, exist_ok=True)
    WEB_VECTORS_PATH.write_bytes(render_web_vectors())


if __name__ == "__main__":
    main()
