import { readFileSync } from "fs";
import { dirname, resolve } from "path";
import { fileURLToPath } from "url";
import { describe, expect, it } from "vitest";

const testDir = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(testDir, "../../../..");
const pyBundlePath = resolve(projectRoot, "src/gobby/install/shared/setup/setup.mjs");
const distBundlePath = resolve(projectRoot, "web/dist-setup/cli.mjs");
const generatedMarker = "Generated by web/scripts/build-setup.mjs; do not edit.";

describe("setup bundle FalkorDB contract", () => {
  it("is regenerated with FalkorDB flags and state fields", () => {
    const bundle = readFileSync(pyBundlePath, "utf-8");

    expect({
      hasGeneratedMarker: bundle.startsWith(`#!/usr/bin/env node\n// ${generatedMarker}`),
      hasFalkorFlag: bundle.includes("--falkordb"),
      hasFalkorPasswordFlag: bundle.includes("--falkordb-password"),
      hasFalkorInstalled: bundle.includes("falkordb_installed"),
      hasFalkorPasswordSet: bundle.includes("falkordb_password_set"),
      hasNeo4jFlag: bundle.includes("--neo4j"),
      hasNeo4jPasswordFlag: bundle.includes("--neo4j-password"),
      hasNeo4jInstalledMigrator: bundle.includes("neo4j_installed"),
      hasNeo4jPasswordSetMigrator: bundle.includes("neo4j_password_set"),
    }).toEqual({
      hasGeneratedMarker: true,
      hasFalkorFlag: true,
      hasFalkorPasswordFlag: true,
      hasFalkorInstalled: true,
      hasFalkorPasswordSet: true,
      hasNeo4jFlag: false,
      hasNeo4jPasswordFlag: false,
      hasNeo4jInstalledMigrator: true,
      hasNeo4jPasswordSetMigrator: true,
    });
  });

  it("keeps the checked-in npm and Python setup bundles byte-identical", () => {
    expect(readFileSync(pyBundlePath)).toEqual(readFileSync(distBundlePath));
  }, 15000);
});
