"""
Claude Code transcript parser.

Parses JSONL transcript files generated by Claude Code CLI.
"""

from __future__ import annotations

import json
import logging
from collections.abc import Iterable, Iterator
from datetime import UTC, datetime
from typing import Any, ClassVar

from gobby.sessions.transcripts.base import (
    UNMODELED_RECORD_CONTENT_TYPE,
    BaseTranscriptParser,
    ParsedMessage,
    ParseEvent,
    RawLine,
    TokenUsage,
    annotate_record_source,
)
from gobby.sessions.transcripts.claude_records import (
    ClaudeMessageBuilder,
    expand_message_content,
    extract_tool_result_content,
    fallback_content,
    system_event_content,
)
from gobby.sessions.transcripts.tool_activity import claude_activity_by_user_index

logger = logging.getLogger(__name__)


def _make_unmodeled_record(
    *, index: int, msg_type: str, data: dict[str, Any], timestamp: datetime
) -> ParsedMessage:
    """Build the non-rendering sentinel for a genuinely-unknown record type.

    Emitted instead of dropping+logging an unrecognized session-envelope record.
    ``render_incremental`` recognizes ``UNMODELED_RECORD_CONTENT_TYPE`` at the top
    of its loop, fires one telemetry observation (T2 worklist), and skips it — no
    card, no group. The real envelope type rides in ``content`` (the renderer
    reads ``block_type=msg.content``). ``timestamp`` is a required
    ``ParsedMessage`` field with no semantic role here; the caller passes the
    record's own timestamp. Provenance (``source`` / ``source_line`` /
    ``source_ref``) is intentionally left ``None`` so ``annotate_record_source``
    fills it with the raw line number on the events path; the direct
    ``parse_line`` fallback resolves it from ``index`` at observation time.
    """
    return ParsedMessage(
        index=index,
        role="system",
        content=str(msg_type or "<missing>"),
        content_type=UNMODELED_RECORD_CONTENT_TYPE,
        tool_name=None,
        tool_input=None,
        tool_result=None,
        timestamp=timestamp,
        raw_json=data,
    )


class ClaudeTranscriptParser(BaseTranscriptParser):
    """
    Parses JSONL transcript files from Claude Code.

    Implements the TranscriptParser protocol for Claude Code's specific
    transcript format. Session boundaries are marked by /clear commands.

    This is a stateless utility class that provides methods for reading,
    parsing, and analyzing transcript files. It does not maintain any
    session state and can be shared across multiple sessions.

    Thread-safe: All methods are stateless and can be called concurrently.
    """

    # Claude Code session-metadata envelope records. These are not conversation
    # content (auto titles, prompt-queue ops, hook traces, mode/permission
    # flags, PR/agent/worktree coordination) and were silently dropped before
    # fail-soft passthrough was added. Recognized here so they are not surfaced
    # as unknown blocks in the chat UI. ``system`` is handled separately
    # (``compact_boundary`` is first-classed as a divider; other subtypes are
    # skipped). ``summary``/``file-history-snapshot`` are listed for
    # forward-compatibility with Claude Code's classic transcript format.
    # ``custom-title`` is the user-set counterpart of ``ai-title`` (not rendered
    # as a title card); ``atis-latch`` carries an opaque per-turn latch token
    # that must never be echoed into the parser-error log.
    _SKIPPED_RECORD_TYPES: ClassVar[frozenset[str]] = frozenset(
        {
            "queue-operation",
            "last-prompt",
            "attachment",
            "agent-name",
            "mode",
            "permission-mode",
            "pr-link",
            "started",
            "result",
            "worktree-state",
            "fork-context-ref",
            "summary",
            "file-history-snapshot",
            "custom-title",
            "atis-latch",
        }
    )

    def __init__(
        self,
        session_id: str | None = None,
        logger_instance: logging.Logger | None = None,
    ):
        """
        Initialize ClaudeTranscriptParser.

        Args:
            session_id: Optional session identifier.
            logger_instance: Optional logger instance to use. If not provided,
                           uses the module-level logger.
        """
        super().__init__(cli_name="claude", session_id=session_id, logger_instance=logger_instance)

    @staticmethod
    def _hook_blocking_attachment(turn: dict[str, Any]) -> dict[str, Any] | None:
        if turn.get("type") != "attachment":
            return None
        attachment = turn.get("attachment")
        if not isinstance(attachment, dict) or attachment.get("type") != "hook_blocking_error":
            return None
        return attachment

    @staticmethod
    def _extract_hook_blocking_content(attachment: dict[str, Any]) -> str:
        error = attachment.get("blockingError")
        if isinstance(error, dict):
            content = error.get("blockingError")
            if isinstance(content, str) and content:
                return content
        return "Claude Code hook blocked this tool call."

    def extract_last_messages(
        self,
        turns: list[dict[str, Any]],
        num_pairs: int = 2,
        *,
        include_tool_activity: bool = False,
    ) -> list[dict[str, Any]]:
        """
        Extract last N user<>agent message pairs from transcript.

        Args:
            turns: List of transcript turns
            num_pairs: Number of user/agent message pairs to extract (default: 2)

        Returns:
            List of message dicts with "role" and "content" fields, ordered chronologically

        Example:
            >>> parser = ClaudeTranscriptParser()
            >>> messages = parser.read_jsonl("/path/to/transcript.jsonl")
            >>> last_msgs = parser.extract_last_messages(messages, num_pairs=3)
            >>> len(last_msgs)
            6  # 3 pairs = 6 messages
        """
        messages: list[dict[str, Any]] = []
        activity = claude_activity_by_user_index(turns) if include_tool_activity else {}
        for turn_index in range(len(turns) - 1, -1, -1):
            turn = turns[turn_index]
            if self._hook_blocking_attachment(turn) is not None:
                continue

            prompt = self._queued_command_prompt(turn)
            if prompt is not None:
                messages.insert(0, {"role": "user", "content": prompt.strip()})
                if len(messages) >= num_pairs * 2:
                    break
                continue

            # Claude Code transcript structure has message nested
            message = turn.get("message", {})
            role = message.get("role")
            if role in ["user", "assistant"]:
                content = message.get("content", "")

                # Assistant messages have content as array of blocks
                if isinstance(content, list):
                    text_parts = []
                    for block in content:
                        if isinstance(block, dict) and block.get("type") == "text":
                            text_parts.append(block.get("text", ""))
                    content = " ".join(text_parts)

                content = str(content).strip()
                if not content:
                    continue

                extracted: dict[str, Any] = {"role": role, "content": content}
                if role == "user" and turn_index in activity:
                    extracted["tool_activity"] = activity[turn_index]
                messages.insert(0, extracted)
                if len(messages) >= num_pairs * 2:
                    break
        return messages

    def extract_turns_since_clear(
        self, turns: list[dict[str, Any]], max_turns: int | None = None
    ) -> list[dict[str, Any]]:
        """
        Extract turns since the most recent /clear.

        Logic:
        1. Find most recent /clear in the transcript (handling consecutive /clears as one boundary)
        2. Start from the turn AFTER the last /clear
        3. If max_turns is set, cap the result size
        4. Consecutive /clear commands are treated as a single conversation boundary

        Args:
            turns: List of all transcript turns
            max_turns: Maximum number of turns to extract (None = no limit)

        Returns:
            List of turns representing the current conversation segment

        Example:
            Turn 100: user message
            Turn 101: /clear
            Turn 102: /clear (consecutive)
            Turn 103: user message
            Turn 104: agent message

            -> Returns turns 103-104 (after the /clear cluster)
        """
        if not turns:
            return []

        # Find the most recent /clear by scanning backwards
        # We want the LAST /clear in any consecutive cluster
        most_recent_clear_idx = None
        for i in range(len(turns) - 1, -1, -1):
            if self.is_session_boundary(turns[i]):
                most_recent_clear_idx = i
                break

        # If no /clear found, return all turns (or last max_turns if capped)
        if most_recent_clear_idx is None:
            result = turns[-max_turns:] if max_turns and len(turns) > max_turns else turns
            result, removed = self._validate_tool_pairing(result)
            if removed:
                self.logger.debug("Removed %s orphaned tool_results: %s", len(removed), removed)
            return result

        # Start after the most recent /clear
        start_idx = most_recent_clear_idx + 1
        end_idx = len(turns)

        # Apply max_turns cap if set
        if max_turns and (end_idx - start_idx) > max_turns:
            start_idx = end_idx - max_turns

            # But make sure we don't cross a /clear boundary
            for i in range(most_recent_clear_idx - 1, start_idx - 1, -1):
                if self.is_session_boundary(turns[i]):
                    boundary_idx = i
                    while boundary_idx < most_recent_clear_idx and self.is_session_boundary(
                        turns[boundary_idx + 1]
                    ):
                        boundary_idx += 1
                    start_idx = boundary_idx + 1
                    break

        result = turns[start_idx:end_idx]
        result, removed = self._validate_tool_pairing(result)
        if removed:
            self.logger.debug("Removed %s orphaned tool_results: %s", len(removed), removed)
        return result

    def is_session_boundary(self, turn: dict[str, Any]) -> bool:
        """
        Check if a turn is a session boundary (/clear command).

        Args:
            turn: Transcript turn dict

        Returns:
            True if turn contains a /clear command marker

        Example:
            >>> parser = ClaudeTranscriptParser()
            >>> content = "<command-name>/clear</command-name>\n<command-message>clear</command-message>"
            >>> turn = {"type": "user", "message": {"content": content}}
            >>> parser.is_session_boundary(turn)
            True
        """
        if turn.get("type") != "user":
            return False

        message = turn.get("message", {})
        content = message.get("content", "")

        return (
            isinstance(content, str)
            and "<command-message>clear</command-message>" in content
            and "<command-name>/clear</command-name>" in content
        )

    def _validate_tool_pairing(
        self, turns: list[dict[str, Any]]
    ) -> tuple[list[dict[str, Any]], list[str]]:
        """Remove orphaned tool_results that reference missing tool_use blocks.

        This prevents Claude API validation errors when truncation cuts between
        a tool_use and its corresponding tool_result.

        Args:
            turns: List of transcript turns to validate

        Returns:
            Tuple of (cleaned turns, list of removed tool_use_ids)
        """
        # Collect valid tool_use_ids from assistant messages
        valid_ids: set[str] = set()
        for turn in turns:
            content = turn.get("message", {}).get("content", [])
            if isinstance(content, list):
                for block in content:
                    if isinstance(block, dict) and block.get("type") == "tool_use":
                        if tid := block.get("id"):
                            valid_ids.add(tid)

        # Filter orphaned tool_results from user messages
        cleaned: list[dict[str, Any]] = []
        removed: list[str] = []
        for turn in turns:
            msg = turn.get("message", {})
            content = msg.get("content", [])
            if isinstance(content, list):
                new_content: list[Any] = []
                for block in content:
                    if isinstance(block, dict) and block.get("type") == "tool_result":
                        tid = block.get("tool_use_id")
                        if tid and tid not in valid_ids:
                            removed.append(tid)
                            continue
                    new_content.append(block)
                if new_content != content:
                    turn = {**turn, "message": {**msg, "content": new_content}}
            cleaned.append(turn)

        return cleaned, removed

    def _parse_data(self, line: str, index: int) -> tuple[dict[str, Any], str, datetime] | None:
        """Parse raw JSON line into (data, msg_type, timestamp) or None if invalid."""
        if not line.strip():
            return None

        try:
            data = json.loads(line)
        except json.JSONDecodeError as e:
            self.error_log.log_decode_failure(
                line_num=index,
                session_id=self.session_id,
                raw_text=line,
                error=e,
            )
            return None

        if not isinstance(data, dict):
            self.error_log.log_decode_failure(
                line_num=index,
                session_id=self.session_id,
                raw_text=line,
                error=None,
            )
            return None

        if data.get("isCompactSummary") is True or data.get("isMeta") is True:
            return None

        msg_type = data.get("type", "unknown")
        timestamp_value = data.get("timestamp")
        if isinstance(timestamp_value, str) and timestamp_value:
            try:
                timestamp = datetime.fromisoformat(timestamp_value.replace("Z", "+00:00"))
            except ValueError:
                timestamp = datetime.now(UTC)
        else:
            timestamp = datetime.now(UTC)

        return data, msg_type, timestamp

    @staticmethod
    def _queued_command_prompt(data: dict[str, Any]) -> str | None:
        attachment = data.get("attachment")
        if not isinstance(attachment, dict) or attachment.get("type") != "queued_command":
            return None
        prompt = attachment.get("prompt")
        return prompt if isinstance(prompt, str) and prompt.strip() else None

    def _expand_line(self, line: str, index: int) -> list[ParsedMessage]:
        """
        Expand a single JSONL line into one or more ParsedMessages.

        Multi-block messages (user messages with tool_result blocks, assistant
        messages with multiple tool_use blocks) are split into separate messages
        so the frontend can render them correctly.
        """
        parsed = self._parse_data(line, index)
        if parsed is None:
            return []

        data, msg_type, timestamp = parsed
        usage, model = self._extract_usage(data)
        message_id = self._message_id_for(data, index)
        results: list[ParsedMessage] = []
        builder = ClaudeMessageBuilder(
            index=index,
            timestamp=timestamp,
            data=data,
            usage=usage,
            model=model,
            message_id=message_id,
        )

        def _make_compaction_summary() -> ParsedMessage:
            meta = data.get("compactMetadata")
            trigger = meta.get("trigger") if isinstance(meta, dict) else None
            text = str(data.get("content") or "Conversation compacted")
            if trigger:
                text = f"{text} ({trigger})"
            # uuid keys the renderer's content dedup so repeated compactions in
            # one transcript each render their own divider.
            uuid = data.get("uuid")
            return builder.make(
                role="system",
                content=text,
                content_type="compaction_summary",
                tool_use_id=uuid if isinstance(uuid, str) else None,
            )

        hook_block = self._hook_blocking_attachment(data)
        if hook_block is not None:
            content = self._extract_hook_blocking_content(hook_block)
            hook_name = hook_block.get("hookName")
            tool_use_id = hook_block.get("toolUseID")
            results.append(
                builder.make(
                    role="tool",
                    content=content,
                    content_type="tool_result",
                    tool_name=hook_name if isinstance(hook_name, str) else None,
                    tool_result={"content": content, "is_error": True},
                    tool_use_id=tool_use_id if isinstance(tool_use_id, str) else None,
                )
            )

        elif msg_type == "user":
            msg_data = data.get("message", {})
            content_val = msg_data.get("content", "")
            results.extend(expand_message_content(builder, content_val, role="user"))

        elif msg_type in ("agent", "assistant"):
            msg_data = data.get("message", {})
            content_blocks = msg_data.get("content", [])
            results.extend(expand_message_content(builder, content_blocks, role="assistant"))

        elif msg_type == "tool_result":
            tr = data.get("result")
            results.append(
                builder.make(
                    role="tool",
                    content=str(tr),
                    content_type="tool_result",
                    tool_name=data.get("tool_name"),
                    tool_result=tr,
                    tool_use_id=data.get("tool_use_id"),
                )
            )
        elif msg_type == "system":
            subtype = data.get("subtype")
            if subtype == "compact_boundary":
                results.append(_make_compaction_summary())
            elif (event_content := system_event_content(data)) is not None:
                results.append(builder.make(role="system", content=event_content))

        elif msg_type == "ai-title":
            ai_title = data.get("aiTitle")
            if isinstance(ai_title, str) and ai_title.strip():
                results.append(
                    builder.make(
                        role="system",
                        content=ai_title,
                        content_type="session_title",
                    )
                )

        elif msg_type == "attachment":
            prompt = self._queued_command_prompt(data)
            if prompt is not None:
                results.append(builder.make(role="user", content=prompt))

        elif msg_type in self._SKIPPED_RECORD_TYPES:
            # Known session-metadata envelope record — recognized, not rendered.
            pass

        else:
            self.error_log.log_unknown_block(index, self.session_id, msg_type, data)
            results.append(
                _make_unmodeled_record(
                    index=index, msg_type=msg_type, data=data, timestamp=timestamp
                )
            )

        return results

    def parse_line(self, line: str, index: int) -> ParsedMessage | None:
        """Parse one line, returning its first normalized record."""
        parsed = self._parse_data(line, index)
        if parsed is None:
            return None

        data, msg_type, timestamp = parsed
        usage, model = self._extract_usage(data)
        message_id = self._message_id_for(data, index)

        role = "unknown"
        content = ""
        content_type = "text"
        tool_name = None
        tool_input = None
        tool_result = None
        tool_use_id = None

        hook_block = self._hook_blocking_attachment(data)
        if hook_block is not None:
            role = "tool"
            content_type = "tool_result"
            content = self._extract_hook_blocking_content(hook_block)
            hook_name = hook_block.get("hookName")
            raw_tool_use_id = hook_block.get("toolUseID")
            tool_name = hook_name if isinstance(hook_name, str) else None
            tool_use_id = raw_tool_use_id if isinstance(raw_tool_use_id, str) else None
            tool_result = {"content": content, "is_error": True}

        elif msg_type == "user":
            role = "user"
            msg_data = data.get("message", {})
            content_val = msg_data.get("content", "")

            if isinstance(content_val, list):
                # Extract text from blocks, handle tool_result blocks gracefully
                text_parts: list[str] = []
                first_tool_result = None
                for block in content_val:
                    if not isinstance(block, dict):
                        continue
                    btype = block.get("type")
                    if btype == "text":
                        text_parts.append(block.get("text", ""))
                    elif btype == "tool_result" and first_tool_result is None:
                        first_tool_result = block

                if text_parts:
                    content = " ".join(text_parts)
                elif first_tool_result:
                    content_type = "tool_result"
                    tr_content = extract_tool_result_content(first_tool_result)
                    content = tr_content
                    tool_use_id = first_tool_result.get("tool_use_id")
                    tool_result = {
                        "content": content,
                        "is_error": first_tool_result.get("is_error", False),
                    }
            else:
                content = str(content_val)

        elif msg_type in ("agent", "assistant"):
            role = "assistant"
            msg_data = data.get("message", {})
            content_blocks = msg_data.get("content", [])

            if isinstance(content_blocks, list):
                text_parts = []
                for block in content_blocks:
                    if not isinstance(block, dict):
                        continue
                    block_type = block.get("type")
                    if block_type == "text":
                        text_parts.append(block.get("text", ""))
                    elif block_type == "tool_use":
                        content_type = "tool_use"
                        tool_name = block.get("name")
                        tool_input = block.get("input")
                        tool_use_id = block.get("id")
                    elif block_type == "fallback":
                        role = "system"
                        text_parts.append(fallback_content(block))
                content = " ".join(text_parts)
            else:
                content = str(content_blocks)

        elif msg_type == "tool_result":
            role = "tool"
            content_type = "tool_result"
            tool_name = data.get("tool_name")
            tool_result = data.get("result")
            tool_use_id = data.get("tool_use_id")
            content = str(tool_result)

        elif msg_type == "system":
            subtype = data.get("subtype")
            if subtype == "compact_boundary":
                role = "system"
                content_type = "compaction_summary"
                meta = data.get("compactMetadata")
                trigger = meta.get("trigger") if isinstance(meta, dict) else None
                content = str(data.get("content") or "Conversation compacted")
                if trigger:
                    content = f"{content} ({trigger})"
                uuid = data.get("uuid")
                tool_use_id = uuid if isinstance(uuid, str) else None
            elif (event_content := system_event_content(data)) is not None:
                role = "system"
                content = event_content
            else:
                return None

        elif msg_type == "ai-title":
            ai_title = data.get("aiTitle")
            if not isinstance(ai_title, str) or not ai_title.strip():
                return None
            role = "system"
            content = ai_title
            content_type = "session_title"

        elif msg_type == "attachment":
            prompt = self._queued_command_prompt(data)
            if prompt is None:
                return None
            role = "user"
            content = prompt

        elif msg_type in self._SKIPPED_RECORD_TYPES:
            return None  # known session-metadata envelope record — not rendered

        else:
            self.error_log.log_unknown_block(index, self.session_id, msg_type, data)
            return _make_unmodeled_record(
                index=index, msg_type=msg_type, data=data, timestamp=timestamp
            )

        return ParsedMessage(
            index=index,
            role=role,
            content=content,
            content_type=content_type,
            tool_name=tool_name,
            tool_input=tool_input,
            tool_result=tool_result,
            timestamp=timestamp,
            raw_json=data,
            usage=usage,
            tool_use_id=tool_use_id,
            model=model,
            message_id=message_id,
        )

    def _extract_usage(self, data: dict[str, Any]) -> tuple[TokenUsage | None, str | None]:
        """Extract token usage and model from message data.

        Returns:
            Tuple of (TokenUsage | None, model string | None)
        """
        message = data.get("message")
        model = message.get("model") if isinstance(message, dict) else data.get("fallbackModel")

        # Check for top-level usage field (some formats)
        usage_data = data.get("usage")

        # Check inside message object (standard Claude API format)
        if not usage_data:
            usage_data = data.get("message", {}).get("usage")

        if not usage_data:
            return None, model

        # Use explicit presence checks to handle 0 correctly
        input_tokens = (
            usage_data["input_tokens"]
            if "input_tokens" in usage_data
            else usage_data.get("inputTokens", 0)
        )
        output_tokens = (
            usage_data["output_tokens"]
            if "output_tokens" in usage_data
            else usage_data.get("outputTokens", 0)
        )
        cache_creation_tokens = (
            usage_data["cache_creation_input_tokens"]
            if "cache_creation_input_tokens" in usage_data
            else usage_data.get("cacheCreationInputTokens", 0)
        )
        cache_read_tokens = (
            usage_data["cache_read_input_tokens"]
            if "cache_read_input_tokens" in usage_data
            else usage_data.get("cacheReadInputTokens", 0)
        )

        return TokenUsage(
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            cache_creation_tokens=cache_creation_tokens,
            cache_read_tokens=cache_read_tokens,
        ), model

    def _message_id_for(self, data: dict[str, Any], index: int) -> str | None:
        """Return a stable Claude message identifier for deduping token events."""
        message = data.get("message")
        if isinstance(message, dict):
            raw_id = message.get("id")
            if isinstance(raw_id, str) and raw_id.strip():
                return raw_id.strip()
        if self.session_id:
            return f"{self.session_id}:claude:{index}"
        return f"claude:{index}"

    def iter_parse_events(
        self, raw_lines: Iterable[RawLine], start_index: int = 0
    ) -> Iterator[ParseEvent]:
        """
        Stream parse events, expanding multi-block lines.

        Each JSONL line may produce multiple ParsedMessages (e.g. an assistant
        message with text + two tool_use blocks becomes three messages); indices are
        assigned **per parsed message** from ``start_index``.
        """
        current_index = start_index
        for cur in raw_lines:
            start_idx = current_index
            expanded = self._expand_line(cur.text, current_index)
            for msg in expanded:
                msg.index = current_index
                current_index += 1

            if expanded:
                records = annotate_record_source(
                    expanded,
                    source=self.cli_name,
                    raw_line_no=cur.raw_line_no,
                )
                yield ParseEvent(
                    byte_offset=cur.byte_offset,
                    raw_line_no=cur.raw_line_no,
                    parsed_index=start_idx,
                    records=records,
                    parser_safe=True,
                )

    # Backward-compatible alias
    is_clear_command = is_session_boundary
