"""
Codex transcript parser.

Parses JSONL transcript files generated by Codex CLI.

Codex uses an envelope format where each line is:
    {"timestamp": "...", "type": "<line_type>", "payload": {...}}

Line types:
    - response_item: Conversation content (messages, tool calls, tool results)
    - event_msg: Metadata events (task_started, turn_aborted, token_count)
    - session_meta: Session metadata
    - turn_context: Turn context metadata

Only response_item lines produce ParsedMessage objects. Within response_item,
payload.type discriminates:
    - message: User/assistant/developer messages with content blocks
    - function_call: Tool invocation (name, arguments, call_id)
    - function_call_output: Tool result (call_id, output)
"""

from __future__ import annotations

import json
import logging
from datetime import UTC, datetime
from typing import Any

from gobby.sessions.transcripts.base import BaseTranscriptParser, ParsedMessage

logger = logging.getLogger(__name__)

_ROLE_MAP = {
    "developer": "system",
}


class CodexTranscriptParser(BaseTranscriptParser):
    """
    Parses JSONL transcript files from Codex.

    Implements the TranscriptParser protocol for Codex's envelope-based
    transcript format.
    """

    def __init__(
        self,
        session_id: str | None = None,
        logger_instance: logging.Logger | None = None,
    ):
        super().__init__(cli_name="codex", session_id=session_id, logger_instance=logger_instance)

    def extract_last_messages(
        self, turns: list[dict[str, Any]], num_pairs: int = 2
    ) -> list[dict[str, Any]]:
        messages: list[dict[str, str]] = []
        for turn in reversed(turns):
            if turn.get("type") != "response_item":
                continue
            payload = turn.get("payload", {})
            if payload.get("type") != "message":
                continue

            role = payload.get("role", "")
            role = _ROLE_MAP.get(role, role)
            if role not in ("user", "assistant", "system"):
                continue

            content = _extract_text_from_blocks(payload.get("content", []))
            messages.insert(0, {"role": role, "content": content})
            if len(messages) >= num_pairs * 2:
                break
        return messages

    def extract_turns_since_clear(
        self, turns: list[dict[str, Any]], max_turns: int | None = None
    ) -> list[dict[str, Any]]:
        # Find the last session boundary and return turns after it
        last_boundary = -1
        for i, turn in enumerate(turns):
            if self.is_session_boundary(turn):
                last_boundary = i

        result = turns[last_boundary + 1 :]
        if max_turns and len(result) > max_turns:
            result = result[-max_turns:]
        return result

    def is_session_boundary(self, turn: dict[str, Any]) -> bool:
        return turn.get("type") == "session_meta"

    def parse_line(self, line: str, index: int) -> ParsedMessage | None:
        if not line.strip():
            return None

        try:
            data = json.loads(line)
        except json.JSONDecodeError as e:
            self.error_log.log_malformed_line(
                line_num=index,
                session_id=self.session_id,
                raw_text=line,
                error=str(e),
            )
            return None

        if not isinstance(data, dict):
            self.error_log.log_malformed_line(
                line_num=index,
                session_id=self.session_id,
                raw_text=line,
                error="Line is not a JSON object",
            )
            return None

        line_type = data.get("type")
        if line_type != "response_item":
            return None

        payload = data.get("payload")
        if not isinstance(payload, dict):
            return None

        timestamp = _parse_timestamp(data)
        payload_type = payload.get("type")

        if payload_type == "message":
            return self._parse_message(data, payload, index, timestamp)
        elif payload_type == "function_call":
            return self._parse_function_call(data, payload, index, timestamp)
        elif payload_type == "function_call_output":
            return self._parse_function_call_output(data, payload, index, timestamp)
        else:
            self.error_log.log_unknown_block(
                line_num=index,
                session_id=self.session_id,
                block_type=f"response_item/{payload_type}",
                raw=data,
            )
            return None

    def _parse_message(
        self,
        data: dict[str, Any],
        payload: dict[str, Any],
        index: int,
        timestamp: datetime,
    ) -> ParsedMessage | None:
        role = payload.get("role", "")
        role = _ROLE_MAP.get(role, role)
        if not role:
            return None

        content = _extract_text_from_blocks(payload.get("content", []))

        return ParsedMessage(
            index=index,
            role=role,
            content=content,
            content_type="text",
            tool_name=None,
            tool_input=None,
            tool_result=None,
            timestamp=timestamp,
            raw_json=data,
            usage=None,
        )

    def _parse_function_call(
        self,
        data: dict[str, Any],
        payload: dict[str, Any],
        index: int,
        timestamp: datetime,
    ) -> ParsedMessage:
        name = payload.get("name", "unknown")
        arguments_str = payload.get("arguments", "{}")
        try:
            tool_input = json.loads(arguments_str)
        except (json.JSONDecodeError, TypeError):
            tool_input = {"raw": arguments_str}
        call_id = payload.get("call_id")

        return ParsedMessage(
            index=index,
            role="assistant",
            content=f"Tool call: {name}",
            content_type="tool_use",
            tool_name=name,
            tool_input=tool_input,
            tool_result=None,
            timestamp=timestamp,
            raw_json=data,
            usage=None,
            tool_use_id=call_id,
        )

    def _parse_function_call_output(
        self,
        data: dict[str, Any],
        payload: dict[str, Any],
        index: int,
        timestamp: datetime,
    ) -> ParsedMessage:
        output = payload.get("output", "")
        call_id = payload.get("call_id")

        return ParsedMessage(
            index=index,
            role="tool",
            content=str(output),
            content_type="tool_result",
            tool_name=None,
            tool_input=None,
            tool_result={"output": output},
            timestamp=timestamp,
            raw_json=data,
            usage=None,
            tool_use_id=call_id,
        )

    def parse_lines(self, lines: list[str], start_index: int = 0) -> list[ParsedMessage]:
        parsed_messages = []
        current_index = start_index

        for line in lines:
            message = self.parse_line(line, current_index)
            if message:
                parsed_messages.append(message)
                current_index += 1

        return parsed_messages


def _extract_text_from_blocks(content_blocks: Any) -> str:
    """Extract and join text from Codex content block arrays.

    Codex uses input_text blocks for user messages and output_text blocks
    for assistant messages.
    """
    if not isinstance(content_blocks, list):
        return str(content_blocks) if content_blocks else ""

    parts: list[str] = []
    for block in content_blocks:
        if not isinstance(block, dict):
            continue
        block_type = block.get("type", "")
        if block_type in ("input_text", "output_text"):
            text = block.get("text", "")
            if text:
                parts.append(text)
    return " ".join(parts)


def _parse_timestamp(data: dict[str, Any]) -> datetime:
    """Parse ISO timestamp from top-level envelope data."""
    ts_str = data.get("timestamp")
    if ts_str:
        try:
            return datetime.fromisoformat(ts_str.replace("Z", "+00:00"))
        except (ValueError, AttributeError):
            pass
    return datetime.now(UTC)
