"""
Codex transcript parser.

Parses JSONL transcript files generated by Codex CLI.

Codex uses an envelope format where each line is:
    {"timestamp": "...", "type": "<line_type>", "payload": {...}}

Line types:
    - response_item: Conversation content (messages, tool calls, tool results)
    - event_msg: Metadata events (task_started, turn_aborted, token_count)
    - session_meta: Session metadata
    - turn_context: Turn context metadata

Only response_item lines produce ParsedMessage objects. Within response_item,
payload.type discriminates:
    - message: User/assistant/developer messages with content blocks
    - function_call/custom_tool_call/web_search_call: Tool invocation variants
    - function_call_output/custom_tool_call_output: Tool results
"""

from __future__ import annotations

import json
import logging
from datetime import UTC, datetime
from typing import Any

from gobby.sessions.transcripts.base import (
    BaseTranscriptParser,
    ParsedMessage,
    ParsedToolEvent,
    TokenUsage,
)

logger = logging.getLogger(__name__)

_ROLE_MAP = {
    "developer": "system",
}


def _parse_int_token(value: Any, *, default: int = 0) -> int:
    """Parse token counts defensively from transcript payload values."""
    try:
        return int(value or 0)
    except (TypeError, ValueError):
        logger.warning("Invalid Codex token count value %r; using %s", value, default)
        return default


def _parse_tool_payload(value: Any) -> dict[str, Any]:
    """Parse a tool payload value into a dict when possible."""
    if isinstance(value, dict):
        return value
    if isinstance(value, str):
        try:
            parsed = json.loads(value)
        except json.JSONDecodeError:
            return {"raw": value}
        if isinstance(parsed, dict):
            return parsed
        return {"value": parsed}
    return {}


def _normalize_tool_output(output: Any) -> tuple[str, dict[str, Any]]:
    """Normalize tool output for transcript rendering and stats."""
    if isinstance(output, dict):
        return str(output), output
    if isinstance(output, str):
        try:
            parsed = json.loads(output)
        except json.JSONDecodeError:
            return output, {"output": output}
        if isinstance(parsed, dict):
            content = parsed.get("output")
            if isinstance(content, str):
                return content, parsed
            return str(parsed), parsed
        return str(parsed), {"value": parsed}
    return str(output), {"output": output}


class CodexTranscriptParser(BaseTranscriptParser):
    """
    Parses JSONL transcript files from Codex.

    Implements the TranscriptParser protocol for Codex's envelope-based
    transcript format.
    """

    def __init__(
        self,
        session_id: str | None = None,
        logger_instance: logging.Logger | None = None,
    ):
        super().__init__(cli_name="codex", session_id=session_id, logger_instance=logger_instance)

    def extract_last_messages(
        self, turns: list[dict[str, Any]], num_pairs: int = 2
    ) -> list[dict[str, Any]]:
        messages: list[dict[str, str]] = []
        for turn in reversed(turns):
            if turn.get("type") != "response_item":
                continue
            payload = turn.get("payload", {})
            if payload.get("type") != "message":
                continue

            role = payload.get("role", "")
            role = _ROLE_MAP.get(role, role)
            if role not in ("user", "assistant", "system"):
                continue

            content = _extract_text_from_blocks(payload.get("content", []))
            messages.insert(0, {"role": role, "content": content})
            if len(messages) >= num_pairs * 2:
                break
        return messages

    def extract_turns_since_clear(
        self, turns: list[dict[str, Any]], max_turns: int | None = None
    ) -> list[dict[str, Any]]:
        # Find the last session boundary and return turns after it
        last_boundary = -1
        for i, turn in enumerate(turns):
            if self.is_session_boundary(turn):
                last_boundary = i

        result = turns[last_boundary + 1 :]
        if max_turns and len(result) > max_turns:
            result = result[-max_turns:]
        return result

    def is_session_boundary(self, turn: dict[str, Any]) -> bool:
        return turn.get("type") == "session_meta"

    def parse_line(self, line: str, index: int) -> ParsedMessage | ParsedToolEvent | None:
        if not line.strip():
            return None

        try:
            data = json.loads(line)
        except json.JSONDecodeError as e:
            self.error_log.log_malformed_line(
                line_num=index,
                session_id=self.session_id,
                raw_text=line,
                error=str(e),
            )
            return None

        if not isinstance(data, dict):
            self.error_log.log_malformed_line(
                line_num=index,
                session_id=self.session_id,
                raw_text=line,
                error="Line is not a JSON object",
            )
            return None

        line_type = data.get("type")
        payload = data.get("payload")
        if not isinstance(payload, dict):
            return None

        timestamp = _parse_timestamp(data)

        if line_type == "event_msg":
            return self._parse_event_msg(data, payload, index, timestamp)
        if line_type != "response_item":
            return None

        payload_type = payload.get("type")

        if payload_type == "message":
            return self._parse_message(data, payload, index, timestamp)
        if payload_type in {"function_call", "custom_tool_call", "web_search_call"}:
            return self._parse_tool_call(data, payload, index, timestamp)
        if payload_type in {"function_call_output", "custom_tool_call_output"}:
            return self._parse_tool_call_output(data, payload, index, timestamp)
        if payload_type == "reasoning":
            return None

        self.error_log.log_unknown_block(
            line_num=index,
            session_id=self.session_id,
            block_type=f"response_item/{payload_type}",
            raw=data,
        )
        return None

    def _parse_message(
        self,
        data: dict[str, Any],
        payload: dict[str, Any],
        index: int,
        timestamp: datetime,
    ) -> ParsedMessage | None:
        role = payload.get("role", "")
        role = _ROLE_MAP.get(role, role)
        if not role:
            return None

        content = _extract_text_from_blocks(payload.get("content", []))

        return ParsedMessage(
            index=index,
            role=role,
            content=content,
            content_type="text",
            tool_name=None,
            tool_input=None,
            tool_result=None,
            timestamp=timestamp,
            raw_json=data,
            usage=None,
            message_id=self._message_id_for(index, payload.get("id")),
        )

    def _parse_tool_call(
        self,
        data: dict[str, Any],
        payload: dict[str, Any],
        index: int,
        timestamp: datetime,
    ) -> ParsedMessage:
        payload_type = payload.get("type")
        call_id = payload.get("call_id")

        if payload_type == "web_search_call":
            action = payload.get("action")
            if not isinstance(action, dict):
                action = {}
            tool_input = dict(action)
            status = payload.get("status")
            if status is not None:
                tool_input["status"] = status
            name = "WebSearch"
        elif payload_type == "custom_tool_call":
            name = str(payload.get("name") or "unknown")
            tool_input = _parse_tool_payload(payload.get("input"))
            status = payload.get("status")
            if status is not None:
                tool_input.setdefault("status", status)
        else:
            name = str(payload.get("name") or "unknown")
            tool_input = _parse_tool_payload(payload.get("arguments"))

        return ParsedMessage(
            index=index,
            role="assistant",
            content=f"Tool call: {name}",
            content_type="tool_use",
            tool_name=name,
            tool_input=tool_input,
            tool_result=None,
            timestamp=timestamp,
            raw_json=data,
            usage=None,
            tool_use_id=call_id,
            message_id=self._message_id_for(index, payload.get("id") or call_id),
        )

    def _parse_tool_call_output(
        self,
        data: dict[str, Any],
        payload: dict[str, Any],
        index: int,
        timestamp: datetime,
    ) -> ParsedMessage:
        output = payload.get("output", "")
        call_id = payload.get("call_id")
        content, tool_result = _normalize_tool_output(output)

        return ParsedMessage(
            index=index,
            role="tool",
            content=content,
            content_type="tool_result",
            tool_name=None,
            tool_input=None,
            tool_result=tool_result,
            timestamp=timestamp,
            raw_json=data,
            usage=None,
            tool_use_id=call_id,
            message_id=self._message_id_for(index, payload.get("id") or call_id),
        )

    def _parse_event_msg(
        self,
        data: dict[str, Any],
        payload: dict[str, Any],
        index: int,
        timestamp: datetime,
    ) -> ParsedMessage | ParsedToolEvent | None:
        payload_type = payload.get("type")

        if payload_type in ("mcp_tool_call_begin", "mcp_tool_call_end"):
            return self._parse_mcp_tool_call(payload, payload_type, timestamp, data)

        if payload_type != "token_count":
            return None

        info = payload.get("info")
        usage_data: dict[str, Any] = payload
        if isinstance(info, dict):
            nested_usage = info.get("last_token_usage") or info.get("total_token_usage")
            if isinstance(nested_usage, dict):
                usage_data = nested_usage

        input_tokens = _parse_int_token(
            usage_data.get("input_tokens") or usage_data.get("inputTokens")
        )
        cached_input_tokens = _parse_int_token(
            usage_data.get("cached_input_tokens") or usage_data.get("cachedInputTokens") or 0
        )
        output_tokens = _parse_int_token(
            usage_data.get("output_tokens") or usage_data.get("outputTokens")
        )
        reasoning_output_tokens = _parse_int_token(
            usage_data.get("reasoning_output_tokens")
            or usage_data.get("reasoningOutputTokens")
            or 0
        )
        cache_creation_tokens = _parse_int_token(
            usage_data.get("cache_creation_input_tokens")
            or usage_data.get("cacheCreationInputTokens")
            or 0
        )

        usage = TokenUsage(
            input_tokens=max(0, input_tokens - cached_input_tokens),
            output_tokens=output_tokens + reasoning_output_tokens,
            cache_creation_tokens=cache_creation_tokens,
            cache_read_tokens=cached_input_tokens,
        )
        model = (
            usage_data.get("model")
            or payload.get("model")
            or payload.get("model_id")
            or payload.get("modelId")
        )

        return ParsedMessage(
            index=index,
            role="assistant",
            content="",
            content_type="text",
            tool_name=None,
            tool_input=None,
            tool_result=None,
            timestamp=timestamp,
            raw_json=data,
            usage=usage,
            model=str(model) if model else None,
            message_id=self._message_id_for(index, payload.get("message_id") or payload.get("id")),
        )

    def parse_lines(
        self, lines: list[str], start_index: int = 0
    ) -> list[ParsedMessage | ParsedToolEvent]:
        parsed_records: list[ParsedMessage | ParsedToolEvent] = []
        current_index = start_index

        for line in lines:
            record = self.parse_line(line, current_index)
            if record is None:
                continue
            parsed_records.append(record)
            # Only ParsedMessage records consume an index slot; tool events are
            # identified by call_id and don't participate in message ordering.
            if isinstance(record, ParsedMessage):
                current_index += 1

        return parsed_records

    def _parse_mcp_tool_call(
        self,
        payload: dict[str, Any],
        payload_type: str,
        timestamp: datetime,
        raw: dict[str, Any],
    ) -> ParsedToolEvent | None:
        invocation = payload.get("invocation")
        if not isinstance(invocation, dict):
            return None

        arguments = invocation.get("arguments")
        if isinstance(arguments, str):
            try:
                arguments = json.loads(arguments)
            except (json.JSONDecodeError, TypeError):
                arguments = {"raw": arguments}
        if not isinstance(arguments, dict):
            arguments = {}

        duration_ns: int | None = None
        duration = payload.get("duration")
        if isinstance(duration, dict):
            secs = duration.get("secs")
            nanos = duration.get("nanos")
            if isinstance(secs, int) and isinstance(nanos, int):
                duration_ns = secs * 1_000_000_000 + nanos

        result_payload = payload.get("result") if payload_type == "mcp_tool_call_end" else None
        result_value: Any | None = None
        error_value: Any | None = None
        if isinstance(result_payload, dict):
            if "Ok" in result_payload:
                result_value = result_payload["Ok"]
            elif "Err" in result_payload:
                error_value = result_payload["Err"]
            else:
                result_value = result_payload

        return ParsedToolEvent(
            phase="begin" if payload_type == "mcp_tool_call_begin" else "end",
            call_id=payload.get("call_id"),
            server=invocation.get("server"),
            tool=invocation.get("tool"),
            arguments=arguments,
            timestamp=timestamp,
            raw_json=raw,
            result=result_value,
            error=error_value,
            duration_ns=duration_ns,
        )

    def _message_id_for(self, index: int, raw_id: Any = None) -> str:
        if isinstance(raw_id, str) and raw_id.strip():
            return raw_id.strip()
        session_prefix = self.session_id or "codex"
        return f"{session_prefix}:codex:{index}"


def _extract_text_from_blocks(content_blocks: Any) -> str:
    """Extract and join text from Codex content block arrays.

    Codex uses input_text blocks for user messages and output_text blocks
    for assistant messages.
    """
    if not isinstance(content_blocks, list):
        return str(content_blocks) if content_blocks else ""

    parts: list[str] = []
    for block in content_blocks:
        if not isinstance(block, dict):
            continue
        block_type = block.get("type", "")
        if block_type in ("input_text", "output_text"):
            text = block.get("text", "")
            if text:
                parts.append(text)
    return " ".join(parts)


def _parse_timestamp(data: dict[str, Any]) -> datetime:
    """Parse ISO timestamp from top-level envelope data.

    Python 3.11+ ``datetime.fromisoformat`` handles the ``Z`` suffix natively,
    so the previous ``replace("Z", "+00:00")`` is unnecessary on the supported
    runtime (Python 3.13+).
    """
    ts_str = data.get("timestamp")
    if ts_str:
        try:
            return datetime.fromisoformat(ts_str)
        except (ValueError, AttributeError):
            pass
    return datetime.now(UTC)
