"""
Codex transcript parser.

Parses JSONL transcript files generated by Codex CLI.

Codex uses an envelope format where each line is:
    {"timestamp": "...", "type": "<line_type>", "payload": {...}}

Line types:
    - response_item: Conversation content (messages, tool calls, tool results)
    - event_msg: Metadata events (task_started, turn_aborted, token_count)
    - session_meta: Session metadata
    - turn_context: Turn context metadata

Only response_item lines produce ParsedMessage objects. Within response_item,
payload.type discriminates:
    - message: User/assistant/developer messages with content blocks
    - function_call/custom_tool_call/web_search_call: Tool invocation variants
    - function_call_output/custom_tool_call_output: Tool results
"""

from __future__ import annotations

import json
import logging
from collections import deque
from collections.abc import Iterable, Iterator, Mapping
from dataclasses import dataclass
from datetime import UTC, datetime
from typing import Any, Literal

from gobby.adapters.codex_impl.item_normalization import (
    extract_functions_exec_command,
    extract_functions_write_stdin_session_id,
    extract_wait_cell_id,
    extract_yielded_cell_id,
)
from gobby.sessions.transcripts.base import (
    BaseTranscriptParser,
    ParsedMessage,
    ParsedToolEvent,
    ParseEvent,
    RawLine,
    TokenUsage,
    _unknown_block_message,
    annotate_record_source,
)

logger = logging.getLogger(__name__)

_ROLE_MAP = {
    "developer": "system",
}

_NESTED_EXEC_NAMES = frozenset({"exec", "functions.exec"})
_NESTED_WAIT_NAMES = frozenset({"wait", "functions.wait"})
_MAX_PENDING_NESTED_EXEC = 64
_TOOL_CALL_PAYLOAD_TYPES = frozenset(
    {"function_call", "custom_tool_call", "web_search_call", "tool_search_call"}
)
_TOOL_OUTPUT_PAYLOAD_TYPES = frozenset(
    {"function_call_output", "custom_tool_call_output", "tool_search_output"}
)


@dataclass(frozen=True)
class CodexNestedExecOutcome:
    """Definitive nested shell result derived from terminal Codex history."""

    outer_call_id: str
    result_index: int
    command: str
    result: dict[str, Any]
    timestamp: datetime
    raw_json: dict[str, Any]

    @property
    def identity(self) -> str:
        return f"{self.outer_call_id}:{self.result_index}"


@dataclass(frozen=True)
class _PendingNestedExec:
    outer_call_id: str
    literal_command: str | None = None
    cell_id: str | None = None
    session_id: str | None = None

    def to_state(self) -> dict[str, Any]:
        return {
            "outer_call_id": self.outer_call_id,
            "literal_command": self.literal_command,
            "cell_id": self.cell_id,
            "session_id": self.session_id,
        }

    @classmethod
    def from_state(cls, value: Any) -> _PendingNestedExec | None:
        if not isinstance(value, dict):
            return None
        outer_call_id = value.get("outer_call_id")
        literal_command = value.get("literal_command")
        cell_id = value.get("cell_id")
        session_id = value.get("session_id")
        if not isinstance(outer_call_id, str) or not outer_call_id:
            return None
        if literal_command is not None and not isinstance(literal_command, str):
            return None
        if cell_id is not None and not isinstance(cell_id, str):
            return None
        if session_id is not None and not isinstance(session_id, str):
            return None
        return cls(
            outer_call_id=outer_call_id,
            literal_command=literal_command,
            cell_id=cell_id,
            session_id=session_id,
        )


def _is_instruction_dump(content: str) -> bool:
    # Local import: transcript_protocol -> transcript_render_models ->
    # transcripts.base initializes this package, so a top-level import here
    # completes an import cycle that breaks any entry through
    # transcript_protocol itself.
    from gobby.sessions.transcript_protocol import (
        _is_protocol_only_text,
        _looks_like_system_bootstrap_text,
    )

    stripped = content.strip()
    return (
        stripped.casefold().startswith("<user_instructions>")
        or _is_protocol_only_text(stripped)
        or _looks_like_system_bootstrap_text(stripped)
    )


def _parse_int_token(value: Any, *, default: int = 0) -> int:
    """Parse token counts defensively from transcript payload values."""
    try:
        return int(value or 0)
    except (TypeError, ValueError):
        logger.warning("Invalid Codex token count value %r; using %s", value, default)
        return default


def _parse_tool_payload(value: Any) -> dict[str, Any]:
    """Parse a tool payload value into a dict when possible."""
    if isinstance(value, dict):
        return value
    if isinstance(value, str):
        try:
            parsed = json.loads(value)
        except json.JSONDecodeError:
            return {"raw": value}
        if isinstance(parsed, dict):
            return parsed
        return {"value": parsed}
    return {}


def _tool_call_arguments(payload: dict[str, Any]) -> Any:
    tool_input = payload.get("input")
    return tool_input if tool_input is not None else payload.get("arguments")


def _classify_tool_envelope(payload_type: Any) -> Literal["call", "output"] | None:
    if payload_type in _TOOL_CALL_PAYLOAD_TYPES:
        return "call"
    if payload_type in _TOOL_OUTPUT_PAYLOAD_TYPES:
        return "output"
    return None


def _normalize_tool_output(output: Any) -> tuple[str, dict[str, Any]]:
    """Normalize tool output for transcript rendering and stats."""
    if isinstance(output, dict):
        return str(output), output
    if isinstance(output, str):
        try:
            parsed = json.loads(output)
        except json.JSONDecodeError:
            return output, {"output": output}
        if isinstance(parsed, dict):
            content = parsed.get("output")
            if isinstance(content, str):
                return content, parsed
            return str(parsed), parsed
        return str(parsed), {"value": parsed}
    return str(output), {"output": output}


def _tool_search_use_id(payload: dict[str, Any]) -> str | None:
    """Return the ID that pairs Codex tool_search calls and outputs."""
    for key in ("call_id", "id"):
        value = payload.get(key)
        if value is None:
            continue
        text = str(value)
        if text:
            return text
    return None


def _parse_tool_search_input(payload: dict[str, Any]) -> dict[str, Any]:
    """Normalize Codex tool_search query arguments."""
    for key in ("arguments", "input", "content"):
        parsed = _parse_tool_payload(payload.get(key))
        if parsed:
            return dict(parsed)

    tool_input: dict[str, Any] = {}
    for key in ("query", "limit"):
        if key in payload:
            tool_input[key] = payload[key]
    return tool_input


def _tool_search_output(payload: dict[str, Any]) -> Any:
    """Extract the user-visible Codex tool_search output payload."""
    if "output" in payload:
        return payload["output"]

    result: dict[str, Any] = {}
    for key in ("tools", "tools_count", "status", "execution"):
        if key in payload:
            result[key] = payload[key]
    if result:
        return result

    return {key: value for key, value in payload.items() if key not in {"type", "id", "call_id"}}


def _dedupe_pending_tool_search_ids(values: Iterable[str]) -> deque[str]:
    pending: deque[str] = deque()
    seen: set[str] = set()
    for value in values:
        if value in seen:
            continue
        pending.append(value)
        seen.add(value)
    return pending


def _bounded_pending_state(value: Any) -> dict[str, _PendingNestedExec]:
    if not isinstance(value, dict):
        return {}
    pending: dict[str, _PendingNestedExec] = {}
    for key, raw_item in value.items():
        if not isinstance(key, str) or not key:
            continue
        item = _PendingNestedExec.from_state(raw_item)
        if item is not None:
            pending[key] = item
        if len(pending) >= _MAX_PENDING_NESTED_EXEC:
            break
    return pending


def _decoded_exec_results(value: Any) -> list[dict[str, Any]]:
    """Decode exact JSON result objects from custom-tool output blocks."""
    if isinstance(value, str):
        try:
            value = json.loads(value)
        except json.JSONDecodeError:
            return []

    if isinstance(value, list):
        results: list[dict[str, Any]] = []
        for item in value:
            if isinstance(item, dict) and isinstance(item.get("text"), str):
                results.extend(_decoded_exec_results(item["text"]))
            elif isinstance(item, (dict, list, str)):
                results.extend(_decoded_exec_results(item))
        return results

    if not isinstance(value, dict):
        return []
    if any(key in value for key in ("exit_code", "exitCode", "session_id", "sessionId")):
        return [value]
    for wrapper_key in ("content", "output"):
        wrapped = value.get(wrapper_key)
        if isinstance(wrapped, list):
            return _decoded_exec_results(wrapped)
    return []


def _definitive_exit_code(result: dict[str, Any]) -> int | None:
    values = [result[key] for key in ("exit_code", "exitCode") if key in result]
    if not values or any(not isinstance(value, int) or isinstance(value, bool) for value in values):
        return None
    first = values[0]
    return first if all(value == first for value in values) else None


def _exec_session_id(result: dict[str, Any]) -> str | None:
    session_id = result.get("session_id", result.get("sessionId"))
    if isinstance(session_id, str) and session_id:
        return session_id
    if isinstance(session_id, int) and not isinstance(session_id, bool):
        return str(session_id)
    return None


def _explicit_result_command(result: dict[str, Any]) -> str | None:
    values = [result[key] for key in ("cmd", "command") if key in result]
    if not values or any(not isinstance(value, str) or not value for value in values):
        return None
    first = values[0]
    return first if all(value == first for value in values) else None


def _yielded_cell_id(output: Any) -> str | None:
    yielded_cell_id = extract_yielded_cell_id({"tool_output": output})
    if yielded_cell_id is not None or not isinstance(output, str):
        return yielded_cell_id
    try:
        decoded = json.loads(output)
    except json.JSONDecodeError:
        return None
    if isinstance(decoded, (dict, list, str)):
        return extract_yielded_cell_id({"tool_output": decoded})
    return None


class CodexTranscriptParser(BaseTranscriptParser):
    """
    Parses JSONL transcript files from Codex.

    Implements the TranscriptParser protocol for Codex's envelope-based
    transcript format.
    """

    def __init__(
        self,
        session_id: str | None = None,
        logger_instance: logging.Logger | None = None,
    ):
        super().__init__(cli_name="codex", session_id=session_id, logger_instance=logger_instance)
        self._pending_tool_search_use_ids: deque[str] = deque()
        self._pending_nested_exec_calls: dict[str, _PendingNestedExec] = {}
        self._pending_nested_exec_cells: dict[str, _PendingNestedExec] = {}
        self._pending_nested_exec_sessions: dict[str, _PendingNestedExec] = {}

    def snapshot_state(self) -> dict[str, Any]:
        state: dict[str, Any] = {
            "pending_tool_search_use_ids": list(self._pending_tool_search_use_ids)
        }
        if self._pending_nested_exec_calls:
            state["pending_nested_exec_calls"] = {
                key: value.to_state() for key, value in self._pending_nested_exec_calls.items()
            }
        if self._pending_nested_exec_cells:
            state["pending_nested_exec_cells"] = {
                key: value.to_state() for key, value in self._pending_nested_exec_cells.items()
            }
        if self._pending_nested_exec_sessions:
            state["pending_nested_exec_sessions"] = {
                key: value.to_state() for key, value in self._pending_nested_exec_sessions.items()
            }
        return state

    def hydrate_state(self, state: Mapping[str, Any]) -> None:
        raw_queue = state.get("pending_tool_search_use_ids")
        self._pending_tool_search_use_ids = (
            _dedupe_pending_tool_search_ids(
                item for item in raw_queue if isinstance(item, str) and item
            )
            if isinstance(raw_queue, list)
            else deque()
        )
        self._pending_nested_exec_calls = _bounded_pending_state(
            state.get("pending_nested_exec_calls")
        )
        self._pending_nested_exec_cells = _bounded_pending_state(
            state.get("pending_nested_exec_cells")
        )
        self._pending_nested_exec_sessions = _bounded_pending_state(
            state.get("pending_nested_exec_sessions")
        )

    def extract_last_messages(
        self, turns: list[dict[str, Any]], num_pairs: int = 2
    ) -> list[dict[str, Any]]:
        messages: list[dict[str, str]] = []
        for turn in reversed(turns):
            if turn.get("type") != "response_item":
                continue
            payload = turn.get("payload", {})
            if payload.get("type") != "message":
                continue

            role = payload.get("role", "")
            if role not in ("user", "assistant"):
                continue

            content = _extract_text_from_blocks(payload.get("content", []))
            if _is_instruction_dump(content):
                continue
            messages.insert(0, {"role": role, "content": content})
            if len(messages) >= num_pairs * 2:
                break
        return messages

    def extract_turns_since_clear(
        self, turns: list[dict[str, Any]], max_turns: int | None = None
    ) -> list[dict[str, Any]]:
        # Find the last session boundary and return turns after it
        last_boundary = -1
        for i, turn in enumerate(turns):
            if self.is_session_boundary(turn):
                last_boundary = i

        result = turns[last_boundary + 1 :]
        if max_turns and len(result) > max_turns:
            result = result[-max_turns:]
        return result

    def is_session_boundary(self, turn: dict[str, Any]) -> bool:
        return turn.get("type") == "session_meta"

    def parse_line(self, line: str, index: int) -> ParsedMessage | ParsedToolEvent | None:
        record, _ = self._parse_line_with_outcomes(line, index)
        return record

    def _parse_line_with_outcomes(
        self, line: str, index: int
    ) -> tuple[ParsedMessage | ParsedToolEvent | None, list[CodexNestedExecOutcome]]:
        if not line.strip():
            return None, []

        try:
            data = json.loads(line)
        except json.JSONDecodeError as e:
            self.error_log.log_decode_failure(
                line_num=index,
                session_id=self.session_id,
                raw_text=line,
                error=e,
            )
            return None, []

        if not isinstance(data, dict):
            self.error_log.log_decode_failure(
                line_num=index,
                session_id=self.session_id,
                raw_text=line,
                error=None,
            )
            return None, []

        line_type = data.get("type")
        payload = data.get("payload")
        if not isinstance(payload, dict):
            return None, []

        timestamp = _parse_timestamp(data)
        outcomes: list[CodexNestedExecOutcome] = []
        if line_type == "response_item":
            payload_type = payload.get("type")
            envelope = _classify_tool_envelope(payload_type)
            if envelope == "call":
                self._remember_nested_exec_call(payload)
            elif envelope == "output":
                outcomes = self._resolve_nested_exec_output(data, payload, timestamp)

        return self._parse_decoded_line(data, payload, index, timestamp), outcomes

    def _parse_decoded_line(
        self,
        data: dict[str, Any],
        payload: dict[str, Any],
        index: int,
        timestamp: datetime,
    ) -> ParsedMessage | ParsedToolEvent | None:
        line_type = data.get("type")

        if line_type == "event_msg":
            return self._parse_event_msg(data, payload, index, timestamp)
        if line_type != "response_item":
            return None

        payload_type = payload.get("type")

        if payload_type == "message":
            return self._parse_message(data, payload, index, timestamp)
        envelope = _classify_tool_envelope(payload_type)
        if envelope == "call":
            return self._parse_tool_call(data, payload, index, timestamp)
        if envelope == "output":
            return self._parse_tool_call_output(data, payload, index, timestamp)
        if payload_type == "reasoning":
            return None

        block_type = f"response_item/{payload_type or '<missing>'}"
        return _unknown_block_message(
            index=index,
            block_type=block_type,
            raw=payload,
            timestamp=timestamp,
            message_id=self._message_id_for(index, payload.get("id")),
        )

    def _remember_nested_exec_call(self, payload: dict[str, Any]) -> None:
        call_id = payload.get("call_id")
        name = payload.get("name")
        if not isinstance(call_id, str) or not call_id or not isinstance(name, str):
            return

        if name in _NESTED_EXEC_NAMES:
            arguments = _tool_call_arguments(payload)
            literal_command = extract_functions_exec_command(arguments)
            session_id = extract_functions_write_stdin_session_id(arguments)
            if literal_command is None and session_id is not None:
                session_pending = self._pending_nested_exec_sessions.get(session_id)
                if session_pending is not None:
                    self._set_pending(
                        self._pending_nested_exec_calls,
                        call_id,
                        session_pending,
                    )
                return
            pending = _PendingNestedExec(
                outer_call_id=call_id,
                literal_command=literal_command,
            )
            self._set_pending(self._pending_nested_exec_calls, call_id, pending)
            return

        if name not in _NESTED_WAIT_NAMES:
            return
        tool_input = _parse_tool_payload(_tool_call_arguments(payload))
        cell_id = extract_wait_cell_id({"tool_input": tool_input})
        if cell_id is None:
            return
        wait_pending = self._pending_nested_exec_cells.get(cell_id)
        if wait_pending is not None:
            self._set_pending(self._pending_nested_exec_calls, call_id, wait_pending)

    @staticmethod
    def _set_pending(
        pending_map: dict[str, _PendingNestedExec],
        key: str,
        pending: _PendingNestedExec,
    ) -> None:
        if key not in pending_map and len(pending_map) >= _MAX_PENDING_NESTED_EXEC:
            pending_map.pop(next(iter(pending_map)))
        pending_map[key] = pending

    def _resolve_nested_exec_output(
        self,
        data: dict[str, Any],
        payload: dict[str, Any],
        timestamp: datetime,
    ) -> list[CodexNestedExecOutcome]:
        call_id = payload.get("call_id")
        if not isinstance(call_id, str) or not call_id:
            return []
        pending = self._pending_nested_exec_calls.pop(call_id, None)
        if pending is None:
            return []

        output = payload.get("output")
        yielded_cell_id = _yielded_cell_id(output)
        if yielded_cell_id is not None:
            if pending.cell_id is not None and pending.cell_id != yielded_cell_id:
                self._pending_nested_exec_cells.pop(pending.cell_id, None)
            yielded_pending = _PendingNestedExec(
                outer_call_id=pending.outer_call_id,
                literal_command=pending.literal_command,
                cell_id=yielded_cell_id,
                session_id=pending.session_id,
            )
            self._set_pending(
                self._pending_nested_exec_cells,
                yielded_cell_id,
                yielded_pending,
            )
            return []

        if pending.cell_id is not None:
            current = self._pending_nested_exec_cells.get(pending.cell_id)
            if current is not None and current.outer_call_id == pending.outer_call_id:
                self._pending_nested_exec_cells.pop(pending.cell_id, None)

        results = _decoded_exec_results(output)
        terminal_results = [
            result for result in results if _definitive_exit_code(result) is not None
        ]
        if not terminal_results:
            session_ids = {
                session_id
                for result in results
                if (session_id := _exec_session_id(result)) is not None
            }
            if len(results) == 1 and len(session_ids) == 1:
                session_id = next(iter(session_ids))
                if pending.session_id is not None and pending.session_id != session_id:
                    self._pending_nested_exec_sessions.pop(pending.session_id, None)
                session_pending = _PendingNestedExec(
                    outer_call_id=pending.outer_call_id,
                    literal_command=pending.literal_command,
                    session_id=session_id,
                )
                self._set_pending(
                    self._pending_nested_exec_sessions,
                    session_id,
                    session_pending,
                )
            return []

        if pending.session_id is not None:
            current = self._pending_nested_exec_sessions.get(pending.session_id)
            if current is not None and current.outer_call_id == pending.outer_call_id:
                self._pending_nested_exec_sessions.pop(pending.session_id, None)

        derived: list[CodexNestedExecOutcome] = []
        for result_index, result in enumerate(results):
            if _definitive_exit_code(result) is None:
                continue
            command = _explicit_result_command(result)
            if command is None and len(results) == 1:
                command = pending.literal_command
            if command is None:
                continue
            derived.append(
                CodexNestedExecOutcome(
                    outer_call_id=pending.outer_call_id,
                    result_index=result_index,
                    command=command,
                    result=dict(result),
                    timestamp=timestamp,
                    raw_json=data,
                )
            )
        return derived

    def _parse_message(
        self,
        data: dict[str, Any],
        payload: dict[str, Any],
        index: int,
        timestamp: datetime,
    ) -> ParsedMessage | None:
        role = payload.get("role", "")
        role = _ROLE_MAP.get(role, role)
        if not role:
            return None

        content = _extract_text_from_blocks(payload.get("content", []))

        return ParsedMessage(
            index=index,
            role=role,
            content=content,
            content_type="text",
            tool_name=None,
            tool_input=None,
            tool_result=None,
            timestamp=timestamp,
            raw_json=data,
            usage=None,
            message_id=self._message_id_for(index, payload.get("id")),
        )

    def _parse_tool_call(
        self,
        data: dict[str, Any],
        payload: dict[str, Any],
        index: int,
        timestamp: datetime,
    ) -> ParsedMessage:
        payload_type = payload.get("type")
        call_id = payload.get("call_id")

        if payload_type == "tool_search_call":
            call_id = _tool_search_use_id(payload) or f"tool-search-{index}"
            if call_id not in self._pending_tool_search_use_ids:
                self._pending_tool_search_use_ids.append(call_id)
            name = "tool_search"
            tool_input = _parse_tool_search_input(payload)
        elif payload_type == "web_search_call":
            action = payload.get("action")
            if not isinstance(action, dict):
                action = {}
            tool_input = dict(action)
            status = payload.get("status")
            if status is not None:
                tool_input["status"] = status
            name = "WebSearch"
        elif payload_type == "custom_tool_call":
            name = str(payload.get("name") or "unknown")
            tool_input = _parse_tool_payload(_tool_call_arguments(payload))
            status = payload.get("status")
            if status is not None:
                tool_input.setdefault("status", status)
        else:
            name = str(payload.get("name") or "unknown")
            tool_input = _parse_tool_payload(_tool_call_arguments(payload))

        return ParsedMessage(
            index=index,
            role="assistant",
            content=f"Tool call: {name}",
            content_type="tool_use",
            tool_name=name,
            tool_input=tool_input,
            tool_result=None,
            timestamp=timestamp,
            raw_json=data,
            usage=None,
            tool_use_id=call_id,
            message_id=self._message_id_for(index, payload.get("id") or call_id),
        )

    def _parse_tool_call_output(
        self,
        data: dict[str, Any],
        payload: dict[str, Any],
        index: int,
        timestamp: datetime,
    ) -> ParsedMessage:
        payload_type = payload.get("type")
        tool_name = None
        if payload_type == "tool_search_output":
            output = _tool_search_output(payload)
            call_id = _tool_search_use_id(payload)
            if call_id is None:
                call_id = (
                    self._pending_tool_search_use_ids.popleft()
                    if self._pending_tool_search_use_ids
                    else f"tool-search-{index}"
                )
            elif self._pending_tool_search_use_ids:
                try:
                    self._pending_tool_search_use_ids.remove(call_id)
                except ValueError:
                    pass
            tool_name = "tool_search"
        else:
            output = payload.get("output", "")
            call_id = payload.get("call_id")
        content, tool_result = _normalize_tool_output(output)

        return ParsedMessage(
            index=index,
            role="tool",
            content=content,
            content_type="tool_result",
            tool_name=tool_name,
            tool_input=None,
            tool_result=tool_result,
            timestamp=timestamp,
            raw_json=data,
            usage=None,
            tool_use_id=call_id,
            message_id=self._message_id_for(index, payload.get("id") or call_id),
        )

    def _parse_event_msg(
        self,
        data: dict[str, Any],
        payload: dict[str, Any],
        index: int,
        timestamp: datetime,
    ) -> ParsedMessage | ParsedToolEvent | None:
        payload_type = payload.get("type")

        if payload_type in ("mcp_tool_call_begin", "mcp_tool_call_end"):
            return self._parse_mcp_tool_call(payload, payload_type, timestamp, data)

        if payload_type != "token_count":
            return None

        info = payload.get("info")
        usage_data: dict[str, Any] = payload
        if isinstance(info, dict):
            nested_usage = info.get("last_token_usage") or info.get("total_token_usage")
            if isinstance(nested_usage, dict):
                usage_data = nested_usage

        input_tokens = _parse_int_token(
            usage_data.get("input_tokens") or usage_data.get("inputTokens")
        )
        cached_input_tokens = _parse_int_token(
            usage_data.get("cached_input_tokens") or usage_data.get("cachedInputTokens") or 0
        )
        output_tokens = _parse_int_token(
            usage_data.get("output_tokens") or usage_data.get("outputTokens")
        )
        cache_creation_tokens = _parse_int_token(
            usage_data.get("cache_creation_input_tokens")
            or usage_data.get("cacheCreationInputTokens")
            or 0
        )

        usage = TokenUsage(
            input_tokens=max(0, input_tokens - cached_input_tokens),
            output_tokens=output_tokens,
            cache_creation_tokens=cache_creation_tokens,
            cache_read_tokens=cached_input_tokens,
        )
        model = (
            usage_data.get("model")
            or payload.get("model")
            or payload.get("model_id")
            or payload.get("modelId")
        )

        return ParsedMessage(
            index=index,
            role="assistant",
            content="",
            content_type="usage",
            tool_name=None,
            tool_input=None,
            tool_result=None,
            timestamp=timestamp,
            raw_json=data,
            usage=usage,
            model=str(model) if model else None,
            message_id=self._message_id_for(index, payload.get("message_id") or payload.get("id")),
        )

    def iter_parse_events(
        self, raw_lines: Iterable[RawLine], start_index: int = 0
    ) -> Iterator[ParseEvent]:
        """Stream events with per-ParsedMessage indexing (no forward lookahead).

        Mirrors the original batch ``parse_lines``: each non-skipped line yields one
        event; only ``ParsedMessage`` records consume an index slot (tool events are
        identified by call_id and don't participate in message ordering). Every event
        is ``parser_safe`` since Codex has no cross-line lookahead.
        """
        current_index = start_index
        for raw in raw_lines:
            record, outcomes = self._parse_line_with_outcomes(raw.text, current_index)
            if record is None and not outcomes:
                continue
            records = annotate_record_source(
                [record] if record is not None else [],
                source=self.cli_name,
                raw_line_no=raw.raw_line_no,
            )
            yield ParseEvent(
                byte_offset=raw.byte_offset,
                raw_line_no=raw.raw_line_no,
                parsed_index=current_index,
                records=records,
                parser_safe=True,
                codex_exec_outcomes=outcomes,
            )
            if isinstance(record, ParsedMessage):
                current_index += 1

    def _parse_mcp_tool_call(
        self,
        payload: dict[str, Any],
        payload_type: str,
        timestamp: datetime,
        raw: dict[str, Any],
    ) -> ParsedToolEvent | None:
        invocation = payload.get("invocation")
        if not isinstance(invocation, dict):
            return None

        arguments = invocation.get("arguments")
        if isinstance(arguments, str):
            try:
                arguments = json.loads(arguments)
            except (json.JSONDecodeError, TypeError):
                arguments = {"raw": arguments}
        if not isinstance(arguments, dict):
            arguments = {}

        duration_ns: int | None = None
        duration = payload.get("duration")
        if isinstance(duration, dict):
            secs = duration.get("secs")
            nanos = duration.get("nanos")
            if isinstance(secs, int) and isinstance(nanos, int):
                duration_ns = secs * 1_000_000_000 + nanos

        result_payload = payload.get("result") if payload_type == "mcp_tool_call_end" else None
        result_value: Any | None = None
        error_value: Any | None = None
        if isinstance(result_payload, dict):
            if "Ok" in result_payload:
                result_value = result_payload["Ok"]
            elif "Err" in result_payload:
                error_value = result_payload["Err"]
            else:
                result_value = result_payload

        return ParsedToolEvent(
            phase="begin" if payload_type == "mcp_tool_call_begin" else "end",
            call_id=payload.get("call_id"),
            server=invocation.get("server"),
            tool=invocation.get("tool"),
            arguments=arguments,
            timestamp=timestamp,
            raw_json=raw,
            result=result_value,
            error=error_value,
            duration_ns=duration_ns,
        )

    def _message_id_for(self, index: int, raw_id: Any = None) -> str:
        if isinstance(raw_id, str) and raw_id.strip():
            return raw_id.strip()
        session_prefix = self.session_id or "codex"
        return f"{session_prefix}:codex:{index}"


def _extract_text_from_blocks(content_blocks: Any) -> str:
    """Extract and join text from Codex content block arrays.

    Codex uses input_text blocks for user messages and output_text blocks
    for assistant messages.
    """
    if not isinstance(content_blocks, list):
        return str(content_blocks) if content_blocks else ""

    parts: list[str] = []
    for block in content_blocks:
        if not isinstance(block, dict):
            continue
        block_type = block.get("type", "")
        if block_type in ("input_text", "output_text"):
            text = block.get("text", "")
            if text:
                parts.append(text)
    return " ".join(parts)


def _parse_timestamp(data: dict[str, Any]) -> datetime:
    """Parse ISO timestamp from top-level envelope data.

    Python 3.11+ ``datetime.fromisoformat`` handles the ``Z`` suffix natively,
    so the previous ``replace("Z", "+00:00")`` is unnecessary on the supported
    runtime (Python 3.13+).
    """
    ts_str = data.get("timestamp")
    if ts_str:
        try:
            return datetime.fromisoformat(ts_str)
        except (ValueError, AttributeError):
            pass
    return datetime.now(UTC)
