"""Tests for the embedded schema flatten assembler."""

from __future__ import annotations

import hashlib
from pathlib import Path

import pytest

from scripts import flatten_schema

pytestmark = pytest.mark.unit

_HEADER = "-- Generated by scripts/flatten_schema.py. Do not edit by hand.\n"


def _schema_dir(tmp_path: Path) -> Path:
    schema_dir = tmp_path / "schema"
    migrations = schema_dir / "migrations"
    migrations.mkdir(parents=True)
    (schema_dir / "baseline.sql").write_text(
        f"{_HEADER}\n-- gobby:destructive\nCREATE TABLE a (id integer);\n",
        encoding="utf-8",
    )
    (migrations / "376_add_b.sql").write_text(
        "CREATE TABLE b (id integer);\n\nALTER TABLE b ADD COLUMN name text;\n",
        encoding="utf-8",
    )
    (migrations / "377_drop_a.sql").write_text(
        "-- gobby:destructive\nDROP TABLE IF EXISTS a;\n",
        encoding="utf-8",
    )
    (migrations / "378_index_b.sql").write_text(
        "-- gobby:non-transactional\n\nCREATE INDEX CONCURRENTLY IF NOT EXISTS idx_b ON b (id);\n",
        encoding="utf-8",
    )
    (migrations / ".gitkeep").write_text("keep\n", encoding="utf-8")
    return schema_dir


def test_flatten_concatenates_in_order_and_rewrites_transactional_hazards(
    tmp_path: Path,
) -> None:
    schema_dir = _schema_dir(tmp_path)

    text, digest = flatten_schema.flatten(schema_dir, version=419, write=False)

    assert text == (
        f"{_HEADER}"
        "-- baseline@419: flattened from baseline@375 + migrations 376-378.\n"
        "\n"
        "CREATE TABLE a (id integer);\n"
        "\n-- flattened migration 376_add_b.sql\n"
        "CREATE TABLE b (id integer);\n\nALTER TABLE b ADD COLUMN name text;\n"
        "\n-- flattened migration 377_drop_a.sql: destructive; fresh lineages "
        "receipt-stamp it without executing.\n"
        "\n-- flattened migration 378_index_b.sql\n"
        "CREATE INDEX IF NOT EXISTS idx_b ON b (id);\n"
    )
    assert digest == hashlib.sha256(text.encode("utf-8")).hexdigest()
    assert (schema_dir / "migrations" / "376_add_b.sql").exists()
    assert "-- gobby:destructive" in (schema_dir / "baseline.sql").read_text(encoding="utf-8")


def test_write_replaces_baseline_and_removes_migrations(tmp_path: Path) -> None:
    schema_dir = _schema_dir(tmp_path)

    text, digest = flatten_schema.flatten(schema_dir, version=419, write=True)

    assert (schema_dir / "baseline.sql").read_text(encoding="utf-8") == text
    assert sorted(path.name for path in (schema_dir / "migrations").iterdir()) == [".gitkeep"]
    assert digest == hashlib.sha256((schema_dir / "baseline.sql").read_bytes()).hexdigest()


def test_non_contiguous_migrations_are_rejected(tmp_path: Path) -> None:
    schema_dir = _schema_dir(tmp_path)
    (schema_dir / "migrations" / "380_gap.sql").write_text("SELECT 1;\n", encoding="utf-8")

    with pytest.raises(ValueError, match="not contiguous"):
        flatten_schema.flatten(schema_dir, version=419, write=False)


def test_main_reports_the_checksum_of_the_assembled_text(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    schema_dir = _schema_dir(tmp_path)
    text, digest = flatten_schema.flatten(schema_dir, version=419, write=False)

    assert flatten_schema.main(["--schema-dir", str(schema_dir)]) == 0

    assert (
        f"dry run baseline@419 lines={text.count(chr(10))} sha256={digest}"
        in capsys.readouterr().out
    )
